module.exports = {
  name: "Italiano"
  code: "it"
  terms:
    "browser_support": "Burnzone non è supportata dal tuo browser. Per favore aggiornalo con la versione più recente o cambialo con il browser di Mozilla o di Chrome."
    "login_to_comment": "Effettua il login per commentare"
    "login_to_challenge": "Accedi per sfidare"
    "login_with": "Effettua il login con"
    "signup_with": "Registrati con"
    "sign_in": "Accedi"
    "sign_in_using": "Accedi utilizzando"
    "settings": "Impostazioni"
    "or": "o"
    "comment": "Commento"
    "comments": "Commenti"
    "challenges": "Sfide"
    "questions": "Domande"
    "likes": "Mi piace"
    "write_comment": "Condividi i tuoi pensieri ..."
    "write_answer": "Inserisci la tua risposta qui"
    "answered": "risposta"
    "submit": "Invia"
    "cancel": "Cancella"
    "sort_by": "ordinati per"
    "get_burnzone": "Ottieni Commenti BurnZone  "
    "oldest": "Il più vecchio"
    "newest": "Il Più nuovo"
    "points": "Punti"
    "points_short": "pt"
    "answers": "Risposte"
    "votes": "Voti"
    "no_points": "{value} Punti"
    "reply": "Rispondi"
    "reply_in_challenge": "Rispondi durante la sfida"
    "comment_in_challenge": "Commenta durante la sfida"
    "challenge": "Sfida"
    "question": "Domanda"
    "key_point": "Punto chiave"
    "no_all_activities": "{value} Commento (i)"
    "no_comments": "{value} commento (i)"
    "no_challenges": "{value} sfida (e)"
    "no_questions": "{value} domanda (e)"
    "no_answers": "{value} risposta (e)"
    "enter_your_pv": "Inserisci il tuo punto di vista ..."
    "vs": "vs"
    "enter_fb_uid": "Inserisci qui la user id di Facebook "
    "non_verified_user": "L'indirizzo email di questo utente non è stato verificato"
    "logout": "Esci"
    "gravatar_profile": "Profilo su Gravatar"
    "days_ago": "{value} giorno (i) fa"
    "hours_ago": "{value} ora (e) fa"
    "minutes_ago": "{value} minuto (i) fa"
    "ends_in_days": "Finisce in {value} giorno (i)"
    "ends_in_hours": "Finisce ore {value} ora(e)"
    "ends_in_minutes": "Finisce in {value} minuto (i)"
    "challenge_ended": "Finito"
    "ends_now": "Dovrebbe finire da un momento all'altro"
    "just_now": "proprio ora"
    "exact_time": "su {value}"
    "my_profile": "Il mio profilo"
    "challenge_comment": "Punto di vista dello Sfidante: "
    "original_comment": "Sintesi del punto in sfida:"
    "or_login_with": "o accedi con"
    "flag": "Bandiera"
    "answer": "Risposta"
    "share": "Condividi"
    "share_challenge": "Condividi questa sfida:"
    "share_conversation": "Condividi questa conversazione"
    "share_tw": "Condividi su Twitter"
    "share_fb": "Condividi su Facebook"
    "error_loading": "Non siamo stati in grado di caricare questa conversazione."
    "error_embed_sitenotexists": "Nome del sito non valido."
    "error_embed_nourl": "URL conversazione non valida "
    "error_embed_embedlocalhost": "Non è possibile inserire una conversazione sul sito BurnZone."
    "error_embed_forceid": "Il tuo account BurnZone è configurato per forzare gli ID di conversazione ma non ne hai fornito alcuno."
    "error_embed_useqs": "Il tuo account BurnZone è configurato per utilizzare stringhe di chiave di ricerca ma non ne hai fornita nessuna. "
    "error_embed_url_not_reachable": "Il tuo articolo deve essere accessibile al pubblico su Internet."
    "flagged": "Contrassegnato"
    "flagged_challenge": "Questa sfida è stata contrassegnata"
    "change_image": "Imposta la tua immagine"
    "change_your_data": "Cambia i dati del tuo profilo"
    "change_name": "Nome"
    "change_email": "Email"
    "change_submit": "Cambia"
    "use_grav_image": "Gravatar"
    "use_fb_image": "Facebook"
    "error_access_api": "C'è stato un problema durante la gestione della tua richiesta"
    "user_banned": "Al momento sei stato sospeso"
    "create_comment_success": "Il tuo commento è stato creato con successo"
    "create_question_success": "La tua domanda è stata creata con successo"
    "create_answer_success": "La tua risposta è stata creata con successo"
    "create_comment_notallowed": "Per il momento sei stato sospeso dal commentare"
    "create_comment_approval": "Il tuo commento attende l'approvazione del moderatore"
    "create_question_approval": "La tua domanda attende l'approvazione del moderatore"
    "create_answer_approval": "La tua risposta attende l'approvazione del moderatore"
    "create_challenge_success": "La tua sfida è stata creata con successo"
    "create_challenge_notallowed": "Per il momento sei stato sospeso dai commenti di sfida"
    "create_challenge_approval": "La tua sfida attende l'approvazione del moderatore"
    "create_challenge_notpoints": "Non hai abbastanza punti per controbattere questo commento"
    "create_challenge_denied": "Non puoi controbbattere il tuo parere, un commento che non esiste, un commento eliminato o un commento che è stato contestato prima (la contestazione potrebbe non essere  approvata)"
    "vote_commentinch_user_in_challenge": "Non puoi votare perché sei in sfida"
    "vote_commentinch_once": "Puoi votare solo una volta e puoi cancellare solo il tuo voto precedente"
    "vote_ch_ended": "Non puoi votare in una sfida che si è conclusa"
    "like_comment_once": "È possibile scrivere il 'mi piace' una sola volta e puoi cancellare solo il tuo 'mi piace' precedente  "
    "like_comment_retry": "C'è stato un conflitto nella tua richiesta. Per favore riprova."
    "like_own_comment": "Non puoi mettere il 'mi piace' al tuo commento "
    "like_author_unknown": "Qualcuno"
    "needs_login": "Prima devi effettuare il log in "
    "needs_moderator": "Per questo hai bisogno dei permessi del moderatore "
    "user_exists": "Questo indirizzo email è già utilizzato da un altro utente. Prova con un altro."
    "edit_profile": "È possibile modificare il nome e l'avatar dalla pagina del tuo profilo"
    "delete": "Cancella"
    "top_answer": "Risposta Migliore"
    "create_user": "Oppure crea un utente BurnZone"
    "create_user_expl": "Creare un utente ti permetterà di commentare, votare e far parte della classifica."
    "anon_name": "Nome"
    "anon_email": "Email"
    "anon_pass": "Password"
    "invalid_name": "Per favore inserisci un nome"
    "invalid_email": "Per favorte inseririsci un indirizzo email valido"
    "invalid_password": " Per favore inserisci una password valida"
    "email_must_be_valid": "Deve essere valido per verificare"
    "site_leaderboard": "Sito Classifica "
    "conversation_leaderboard": "Classifica Conversazione"
    "site_leaderboard_title": "Queste classifiche sono basate su tutte le attività che gli utenti hanno in tutto il sito"
    "conversation_leaderboard_title": "Queste classifiche sono basate sull'attività di questo singolo articolo"
    "how_to_points": "Come faccio ad avere punti?"
    "not_verified": " Il tuo indirizzo e-mail non è verificato. Non sei autorizzato a segnalare i contenuti inappropriati e puoi votare per un numero limitato di volte."
    "no_password": "Non è stata ancora impostata una password  e potresti perdere il tuo account. <a href=\"#{"#profile"}\"> Vai al tuo profilo </a> poi fai clic su \" Modifica password \" per impostare una password per il tuo account."
    "change_pass": " <a href=\"{url}/profile\" target=\"_blank\"> modifica la password </a>."
    "change_notifications": " <a href=\"{url}/profile\" target=\"_blank\"> Modifica le opzioni di notifica </a>."
    "subscription_options": "Opzioni di sottoscrizione"
    "subscribe": "Abbonarsi"
    "subscribe_own": "Iscriviti al mio contenuto"
    "subscribe_auto": "Iscrizione automatica alle conversazioni a cui prendo parte"
    "subscribe_conversations": "Iscriviti a nuovi articoli"
    "subscribe_updates": "Iscriviti agli aggiornamenti in questa conversazione"
    "subscribe_success": "Ti sei iscritto con successo"
    "unsubscribe_success": "Ti sei cancellato con successo "
    "read_more": "(Leggi di più)"
    "read_less": "(Leggi di meno) "
    "show_more": "Mostra di più"
    "delete_all": "Elimina tutto"
    "format_text": "Formattazione del testo"
    "challenge_ad_text": "Non sei d'accordo con un commento?"
    "challenge_ad_text_2": "Sfida per ricevere punti."
    "learn_more": "Per saperne di più"
    "best_answer": "Miglior Risposta"
    "challenged_comment": "Commento contestato"
    "challenged_question": "Domanda contestata"
    "go_to_comments": "Torna ai commenti"
    "is_question": "Questa è una domanda"
    "comment_deleted": "Questo commento è stato eliminato"
    "question_deleted": "Questa domanda è stata cancellata"
    "answer_deleted": "Questa risposta è stata cancellata"
    "challenge_deleted": "Questa sfida è stata cancellata"
    "said": "Detto"
    "challenged": "Contestato"
    "challenge_winner": "Vincitore sfida"
    "title_like_up": "Mi piace questo commento"
    "title_like_down": "Non mi piace questo  commento"
    "title_best_answer": "Questa è la migliore risposta, in base ai voti ricevuti"
    "title_challenged": "Questo commento è stato contestato"
    "title_reply": "Rispondi a questo commento"
    "title_challenge": "Sfida questo commento per condividere una visione differente"
    "title_share": "Condividi sui social media"
    "title_flag": "Contrassegna come spam"
    "title_vote_up": "Vota "
    "title_vote_down": "Ritira il voto"
    "title_challenged_side": "Questo è il commento che è stato contestato.  Vota se sei d'accordo con il commentatore."
    "title_challenger_side": "Questa è l'opinione dello sfidante. Vota se sei d'accordo con il suo  punto di vista differente. "
    "title_reply_comment": "Commenta questa opinione"
    "title_reply_question": "Commenta questa domanda"
    "title_reply_answer": "Commenta questa risposta"
    "title_reply_challenge": "Commenta questa sfida"
    "title_question_answer": "Rispondi a questa domanda"
    "title_answer_note": "Questa è una risposta alla domanda di cui sopra"
    "title_is_question": "Controlla questo se stai postando una domanda"
    "title_logo": "Commenti BurnZone "
    "new_notifications": "{value}"
    "user_notif_NEW_CONVERSATION": "Un nuovo articolo è stato pubblicato su {sitename}"
    "user_notif_WIN_QUESTION": "Hai avuto la risposta migliore!"
    "user_notif_WIN_QUESTION_here": "Avete avuto la  risposta migliore!"
    "user_notif_NEW_COMMENT": "Nuovo commento"
    "user_notif_NEW_COMMENT_here": "Nuovo commento"
    "user_notif_ANSWER": "{username} ha risposto al tuo commento"
    "user_notif_ANSWER_here": "{username} ha risposto al vostro commento"
    "user_notif_REPLY": "{username} ha replicato al tuo commento"
    "user_notif_REPLY_here": "{username} j ha replicato al vostro commento"
    "user_notif_CHALLENGED": "{username} ha sfidato il tuo commento"
    "user_notif_CHALLENGED_here": "{username} ha sfidato il vostro commento"
    "user_notif_NEW_CHALLENGE": "Nuova sfida"
    "user_notif_NEW_CHALLENGE_here": "Nuova sfida"
    "user_notif_WIN_CHALLENGE": "Hai vinto la tua sfida!"
    "user_notif_WIN_CHALLENGE_here": "Avete vinto la vostra sfida!"
    "user_notif_LOSE_CHALLENGE": "Hai perso la tua sfida!"
    "user_notif_LOSE_CHALLENGE_here": "Avete perso la vostra sfida!"
    "user_notif_VOTE": "{username} ti ha votato in una sfida"
    "user_notif_VOTE_here": "{username} vi ha votato in una sfida"
    "user_notif_VOTE_down": "Qualcuno ha ritirato il voto per te in una sfida"
    "user_notif_VOTE_down_here": "Qualcuno ha ritirato il voto per voi in una sfida"
    "user_notif_LIKE_ANSWER": "{username} ha gradito la tua risposta"
    "user_notif_LIKE_ANSWER_here": "{username} ha gradito la vostra risposta"
    "user_notif_LIKE_ANSWER_down": "Qualcuno ha ritirato il voto per la tua risposta"
    "user_notif_LIKE_ANSWER_down_here": "Qualcuno ha ritirato il voto per la vostra risposta"
    "user_notif_LIKE_COMMENT": "{username} ha gradito il tuo commento"
    "user_notif_LIKE_COMMENT_here": "{username} ha gradito il vostro commento"
    "user_notif_LIKE_COMMENT_down": "Qualcuno ha cancellato il 'mi piace'  per il tuo commento"
    "user_notif_LIKE_COMMENT_down_here": "Qualcuno ha cancellato il 'mi piace'  per il vostro commento"
    "user_notif_LIKE_ANSWER_UPDOWN": "{username} ha gradito la tua risposta"
    "user_notif_LIKE_ANSWER_UPDOWN_here": "{username}ha gradito la vostra risposta"
    "user_notif_LIKE_ANSWER_UPDOWN_retract": " Qualcuno ha cancellato il 'mi piace'  per la tua risposta"
    "user_notif_LIKE_ANSWER_UPDOWN_retract_here": "Qualcuno ha cancellato il 'mi piace'  per la vostra risposta "
    "user_notif_LIKE_ANSWER_UPDOWN_down": "A qualcuno non piace la tua risposta"
    "user_notif_LIKE_ANSWER_UPDOWN_down_here": "A qualcuno non piace la vostra risposta"
    "user_notif_LIKE_ANSWER_UPDOWN_down_retract": "Qualcuno ha cancellato il 'non mi piace' per la tua risposta"
    "user_notif_LIKE_ANSWER_UPDOWN_down_retract_here": "Qualcuno ha cancellato il 'non mi piace' per la vostra risposta"
    "user_notif_LIKE_COMMENT_UPDOWN": " A {username} è piaciuto il tuo commento"
    "user_notif_LIKE_COMMENT_UPDOWN_here": " A {username} è piaciuto il vostro commento"
    "user_notif_LIKE_COMMENT_UPDOWN_retract": "Qualcuno ha cancellato il mi piace per il tuo commento"
    "user_notif_LIKE_COMMENT_UPDOWN_retract_here": "Qualcuno ha cancellato il mi piace per il vostro commento"
    "user_notif_LIKE_COMMENT_UPDOWN_down": "Qualcuno ha messo il 'non mi piace' sul tuo commento "
    "user_notif_LIKE_COMMENT_UPDOWN_down_here": "Qualcuno ha messo il 'non mi piace' sul vostro commento "
    "user_notif_LIKE_COMMENT_UPDOWN_down_retract": "Qualcuno ha cancellato  il 'non mi piace' sul tuo commento "
    "user_notif_LIKE_COMMENT_UPDOWN_down_retract_here": "Qualcuno ha cancellato il 'non mi piace' dal vostro commento "
    "competitions": "Concorsi"
    "competition_banner": "Concorrenza: <strong> {title} </strong> da {start} a {end}; leggere il <a target='_blank' href='{rules}'> regole </a> e partecipare alla conversazione </a> "
    "competition_header": "<i class='icon-trophy'> </i> Vincere <a href='{prize_url}'> {prize} </a> di adesione {community} comunità e commentando tra {start} - {end} (<span class='countdown'> {countdown} </span> rimanente, vedere <a target='_blank' href='{rules}'> regole </a>) "
    "competition_starts_on": "La concorrenza inizia"
    "competition_active": "La concorrenza è attivo"
    "competition_ended_on": "La concorrenza è concluso il"
    "competition_active_until": "Concorso attiva fino a quando"
    "competition_winner": "Vincitore"
    "competition_rules": "Regole"
    "competition_prize": "Premio"
    "competition_ranking_title": "Concorso Ranking"
    "user_notif_COMPETITION_START": "La concorrenza è iniziato: {title}"
    "user_notif_COMPETITION_STARTING": "{days} giorni fino a inizio gara: {title}"
    "user_notif_COMPETITION_END": "La concorrenza è conclusa: {title}"
    "user_notif_COMPETITION_ENDING": "Concorso {title} termina in {days} giorni"
    "submit_comment": "Invia un commento"
    "submit_question": "Invia domanda"
    "reg_and_submit_comment": "Registro"
}
