module.exports = {
  name: "Polski"
  code: "pl"
  terms:
    "browser_support": " Burnzone nie jest obsługiwana w Twojej przeglądarce. Należy zaktualizować przeglądarkę do najnowszej wersji lub zmienić przeglądarkę na Mozilla lub Chrome."
    "login_to_comment": " Zaloguj się, aby skomentować"
    "login_to_challenge": " Zaloguj się, aby zakwestionować"
    "login_with": " Zaloguj się przez"
    "signup_with": " Zarejestruj się przez"
    "sign_in": " Zarejestruj się"
    "sign_in_using": " Zaloguj się za pomocą"
    "settings": "Ustawienia"
    "or": " lub"
    "comment": " Komentarz"
    "comments": " Komentarze"
    "challenges": " Wyzwania"
    "questions": " Pytania"
    "likes": " upodobania"
    "write_comment": " Podziel się swoimi myślami ..."
    "write_answer": " Wpisz swoją odpowiedź tutaj"
    "answered": " odpowiedziane"
    "submit": "Dostarczyć"
    "cancel": " Anulować"
    "sort_by": " sortowanie według"
    "get_burnzone": " Pobierz BurnZone skomentowaną"
    "oldest": " Najstarsza"
    "newest": " Najnowsza"
    "points": " Punkty"
    "points_short": " pkt"
    "answers": " Odpowiedzi"
    "votes": " Głosy"
    "no_points": " {value} Punkty"
    "reply": " Odpowiedź"
    "reply_in_challenge": " Odpowiedź na wyzwania"
    "comment_in_challenge": " Komentarz w wyzwaniu"
    "challenge": " Wyzwanie"
    "question": "Pytanie"
    "key_point": " Kluczowy punkt"
    "no_all_activities": " {value} Komentarz (e)"
    "no_comments": " {value} komentarz (e)"
    "no_challenges": " {value} wyzwanie (/a)"
    "no_questions": " {value} pytanie (/a)"
    "no_answers": " {value} odpowiedzi"
    "enter_your_pv": " Wpisz twój punkt widzenia ..."
    "vs": " kontra"
    "enter_fb_uid": " Wpisz ID użytkownika Facebook'a"
    "non_verified_user": "Adres e-mail użytkownika nie został zweryfikowany"
    "logout": " Wyloguj się"
    "gravatar_profile": " Profil na Gravatar"
    "days_ago": " {value} dzień (dni) temu"
    "hours_ago": " {value} godzina (y) temu"
    "minutes_ago": " {value} minuta (y) temu"
    "ends_in_days": " Kończy się za {value} dzień (dni)"
    "ends_in_hours": " Kończy się za {value} godzin (y)"
    "ends_in_minutes": " Kończy się za {value} minutę (y)"
    "challenge_ended": " Zakończony"
    "ends_now": " Powinna zakończyć się w każdej chwili"
    "just_now": "właśnie teraz"
    "exact_time": " na {value}"
    "my_profile": " Mój profil"
    "challenge_comment": "Punktu widzenia rzucającego wyzwanie:"
    "original_comment": " Podsumowanie punktu wyzwania:"
    "or_login_with": " lub zaloguj się przez"
    "flag": " Flaga"
    "answer": " Odpowiedź"
    "share": "Podziel się"
    "share_challenge": "podziel się tym wyzwaniem:"
    "share_conversation": " Podziel się tą rozmową"
    "share_tw": " Podziel się na Twitterze"
    "share_fb": " Podziel się na Facebooku"
    "error_loading": " Nie byliśmy w stanie załadować tej rozmowy."
    "error_embed_sitenotexists": " Nieprawidłowa nazwa witryny."
    "error_embed_nourl": " Nieprawidłowy adres URL rozmowy."
    "error_embed_embedlocalhost": " Nie można dodać rozmowy na miejscu BurnZone."
    "error_embed_forceid": " Twoje konto BurnZone jest skonfigurowane do wywołania identyfikatorów konwersacji ale ich nie dostarczyłeś."
    "error_embed_useqs": " Twoje konto BurnZone jest skonfigurowane do korzystania z kluczy ciągu kwerendy, ale nie dostarczyłeś wszystkich."
    "error_embed_url_not_reachable": " Twój artykuł musi być publicznie dostępny w internecie."
    "flagged": " Oflagowany"
    "flagged_challenge": " To wyzwanie zostało oflagowane"
    "change_image": " Ustawić obraz"
    "change_your_data": " Zmienić twoje dane profilu"
    "change_name": "Imię"
    "change_email": " E-mail"
    "change_submit": " Zmienić"
    "use_grav_image": " Gravatar"
    "use_fb_image": " Facebook"
    "error_access_api": " Wystąpił problem podczas obsługi żądania"
    "user_banned": " Zostałeś zablokowany na chwilę"
    "create_comment_success": " Twój komentarz został pomyślnie utworzony"
    "create_question_success": " Twoje pytanie zostało pomyślnie utworzone"
    "create_answer_success": " Twoja odpowiedź została pomyślnie utworzona"
    "create_comment_notallowed": "Twoja opcja komentowania została chwilowo zablokowana "
    "create_comment_approval": " Twój komentarz czeka na zatwierdzenie moderatora"
    "create_question_approval": " Twoje pytanie czeka na zatwierdzenie moderatora"
    "create_answer_approval": " Twoja odpowiedź czeka na zatwierdzenie moderatora"
    "create_challenge_success": " Twoje wyzwanie zostało pomyślnie utworzone"
    "create_challenge_notallowed": "Twoja opcja komentowania wyzwań została chwilowo zablokowana "
    "create_challenge_approval": " Twoje wyzwanie czeka na zatwierdzenie moderatora"
    "create_challenge_notpoints": " Nie masz wystarczającej ilości punktów, aby zakwestionować ten komentarz"
    "create_challenge_denied": " Nie można kwestionować własnej opinii, komentarza, który nie istnieje, który został usunięty, komentarza lub opinii, która została zakwestionowana uprzednio (wyzwanie może być niezatwierdzone)"
    "vote_commentinch_user_in_challenge": " Nie możesz głosować, bo uczestniczysz w wyzwaniu"
    "vote_commentinch_once": " Możesz głosować tylko raz i możesz wycofać tylko twoje poprzednie głosowanie"
    "vote_ch_ended": " Nie możesz głosować w starciu, które się zakończyło"
    "like_comment_once": " Możesz głosować tylko raz i możesz wycofać tylko twoje poprzednie głosowanie"
    "like_comment_retry": " Wystąpił konflikt w twoim wniosku. Prosimy spróbować ponownie."
    "like_own_comment": " Nie można głosować na własny komentarz"
    "like_author_unknown": " Ktoś"
    "needs_login": " Musisz się najpierw zalogować"
    "needs_moderator": " Trzeba do tego zezwolenia moderatora"
    "user_exists": " Ten adres e-mail jest już używany przez innego użytkownika. Proszę spróbować inny."
    "edit_profile": " Możesz zmienić nazwę i avatar z twojego profilu"
    "delete": " Usunąć"
    "top_answer": " Najlepsza odpowiedź"
    "create_user": " Lub utworzyć użytkownika BurnZone"
    "create_user_expl": " Stworzenie użytkownika umożliwi ci komentowanie, głosowanie i bycie częścią tablicy."
    "anon_name": "Imię"
    "anon_email": " E-mail"
    "anon_pass": " Hasło"
    "invalid_name": " Proszę wpisać imię"
    "invalid_email": " Proszę wpisać poprawny adres email"
    "invalid_password": " Proszę wpisać poprawne hasło"
    "email_must_be_valid": " Musi być poprawne, aby można było sprawdzić"
    "site_leaderboard": " Ranking strony"
    "conversation_leaderboard": " Rozmowa liderów"
    "site_leaderboard_title": " Te rankingi są oparte na wszystkich działaniach, które użytkownicy mają na całej stronie"
    "conversation_leaderboard_title": " Rankingi są oparte na aktywności tego jednego artykułu"
    "how_to_points": " Jak dostać punkty?"
    "not_verified": " Twój adres e-mail nie został zweryfikowany. Nie masz uprawnień do flagowania nieodpowiednich treści i możesz głosować ograniczoną ilość razy."
    "no_password": " Nadal nie ustaliłeś hasła, ale i możesz stracić twoje konto. <a href=\"#{"#profile"}\"> Idź do twojego profilu </a>, a następnie kliknij przycisk Zmień hasło \" \", aby ustawić hasło dla twojego konta."
    "change_pass": " <a href=\"{url}/profile\" target=\"_blank\"> Zmień hasło </a>."
    "change_notifications": " <a href=\"{url}/profile\" target=\"_blank\"> Zmień opcje powiadomień </a>."
    "subscription_options": " Opcje subskrypcji"
    "subscribe": " Subskrybować"
    "subscribe_own": " Zapisz się do mojej własnej treści"
    "subscribe_auto": " Auto subskrybować rozmowy w których biorę udział "
    "subscribe_conversations": " Zapisz się do nowych artykułów"
    "subscribe_updates": " Zapisz się do aktualizacji w tej rozmowie"
    "subscribe_success": " Pomyślnie zasubskrybowałeś"
    "unsubscribe_success": " Udało ci się pomyślnie odsubskrybować"
    "read_more": " (Przeczytaj więcej)"
    "read_less": " (Przeczytaj mniej)"
    "show_more": " Pokaż więcej"
    "delete_all": " Usuń wszystko"
    "format_text": " Formatowanie tekstu"
    "challenge_ad_text": " Nie zgadzasz się z komentarzem?"
    "challenge_ad_text_2": "Rzucić wyzwanie aby otrzymać punkty."
    "learn_more": " Dowiedz się więcej"
    "best_answer": " Najlepsza odpowiedź"
    "challenged_comment": " Komentarz zakwestionowany"
    "challenged_question": " Pytanie zakwestionowane"
    "go_to_comments": " Wróć do komentarzy"
    "is_question": " To jest pytanie"
    "comment_deleted": " Ten komentarz został usunięty"
    "question_deleted": " To pytanie zostało usunięte"
    "answer_deleted": " Ta odpowiedź została usunięta"
    "challenge_deleted": " To wyzwanie zostało usunięte"
    "said": " powiedziane"
    "challenged": " kwestionowane"
    "challenge_winner": " Rzucić wyzwanie zwycięzcy"
    "title_like_up": " Podoba mi się ten komentarz"
    "title_like_down": " Nie podoba mi się ten komentarz"
    "title_best_answer": " To jest najlepsza odpowiedź, na podstawie otrzymanych głosów"
    "title_challenged": " Ten komentarz został zakwestionowany"
    "title_reply": " Odpowiedz na ten komentarz"
    "title_challenge": " Zakwestionuj ten komentarz do podzielenia się odmienną opinią"
    "title_share": " Podziel się tym na mediach społecznościowych"
    "title_flag": "Oznacz jako spam"
    "title_vote_up": " Głosuj pozytywnie"
    "title_vote_down": " Wycofać głos"
    "title_challenged_side": " To jest komentarz, który został zakwestionowany. Głosuj, jeśli zgadzasz się z tym odmiennym komentarzem."
    "title_challenger_side": " To jest opinia rzucającego wyzwanie. Głosuj, jeśli zgadzasz się z tym punktem widzenia przeciwnika."
    "title_reply_comment": " Skomentuj tę opinię"
    "title_reply_question": " Skomentuj to pytanie"
    "title_reply_answer": " Skomentuj tę odpowiedź"
    "title_reply_challenge": " Skomentuj to wyzwanie"
    "title_question_answer": " Odpowiedz na to pytanie"
    "title_answer_note": " To jest odpowiedź na powyższe pytanie"
    "title_is_question": " Sprawdź to, jeśli publikujesz pytanie"
    "title_logo": " BurnZone skomentowane"
    "new_notifications": " {value}"
    "user_notif_NEW_CONVERSATION": " Nowy artykuł został opublikowany na {sitename}"
    "user_notif_WIN_QUESTION": " Miałeś najlepszą odpowiedź!"
    "user_notif_WIN_QUESTION_here": " Miałeś najlepszą odpowiedź!"
    "user_notif_NEW_COMMENT": " Nowy komentarz"
    "user_notif_NEW_COMMENT_here": " Nowy komentarz"
    "user_notif_ANSWER": " {username} odpowiedział na twój komentarz"
    "user_notif_ANSWER_here": " {username} odpowiedział na twój komentarz"
    "user_notif_REPLY": " {username} odpowiedział na twój komentarz"
    "user_notif_REPLY_here": " {username} odpowiedział na twój komentarz"
    "user_notif_CHALLENGED": " {username} zakwestionował twój komentarz"
    "user_notif_CHALLENGED_here": " {username} zakwestionował twój komentarz"
    "user_notif_NEW_CHALLENGE": " Nowe wyzwanie"
    "user_notif_NEW_CHALLENGE_here": " Nowe wyzwanie"
    "user_notif_WIN_CHALLENGE": " Wygrałeś twoje wyzwanie!"
    "user_notif_WIN_CHALLENGE_here": " Wygrałeś twoje wyzwanie!"
    "user_notif_LOSE_CHALLENGE": "Przegrałeś wyzwanie!"
    "user_notif_LOSE_CHALLENGE_here": "Przegrałeś wyzwanie!"
    "user_notif_VOTE": " {username} głosował na ciebie w starciu"
    "user_notif_VOTE_here": " {username} głosował na ciebie w starciu"
    "user_notif_VOTE_down": " Ktoś wycofał swój głos na twoje wyzwanie"
    "user_notif_VOTE_down_here": " Ktoś wycofał swój głos na twoje wyzwanie"
    "user_notif_LIKE_ANSWER": " {username} poparł twoją odpowiedź"
    "competitions": "Konkursy"
    "competition_banner": "Konkurs: <strong> {title} </strong> {start}, aby {end}; przeczytać <a target='_blank' href='{rules}'> Zasady </a> i dołączyć do rozmowy </a> "
    "competition_header": "<i class='icon-trophy'> </i> Wygraj <a href='{prize_url}'> {prize} </a> przez przystąpienie do społeczności {community} i komentując między {start} - {end} (odliczanie <span class='countdown'> {countdown} </span> pozostałe, patrz <a target='_blank' href='{rules}'> zasady </a>) "
    "competition_starts_on": "Konkurs rozpoczyna się"
    "competition_active": "Konkurs jest aktywna"
    "competition_ended_on": "Konkurs zakończony"
    "competition_active_until": "Konkurs aktywna do momentu"
    "competition_winner": "Zwycięzca"
    "competition_rules": "Regulamin"
    "competition_prize": "Nagroda"
    "competition_ranking_title": "Konkurencja w rankingu"
    "user_notif_COMPETITION_START": "Konkurs rozpoczęty: {title}"
    "user_notif_COMPETITION_STARTING": "{days} dni do rozpoczęcia konkursu: {title}"
    "user_notif_COMPETITION_END": "Konkurs zakończony: {title}"
    "user_notif_COMPETITION_ENDING": "Konkurencja {title} kończące się {days} dni"
    "submit_comment": "Dodaj komentarz"
    "submit_question": "Wyślij pytanie"
    "reg_and_submit_comment": "Zarejestruj się"
}
