module.exports = {
  name: "Français"
  code: "fr"
  terms:
    "browser_support": " Burnzone n'est pas pris en charge par votre navigateur. Veuillez le mettre à jour ou télécharger les navigateurs Mozilla ou Chrome."
    "login_to_comment": " Connectez-vous pour commenter"
    "login_to_challenge": " Connectez-vous pour répondre"
    "login_with": " Connectez-vous avec"
    "signup_with": "Inscrivez-vous avec"
    "sign_in": "S'inscrire"
    "sign_in_using": " Connectez-vous en utilisant"
    "settings": "Paramètres"
    "or": "Commenter"
    "comment": " Commentaire"
    "comments": " Commentaires"
    "challenges": " Défis"
    "questions": " Questions"
    "likes": "Aime"
    "write_comment": " Donnez-nous votre avis ..."
    "write_answer": "Entrez votre réponse ici"
    "answered": "réponse apportée"
    "submit": "Soumettre"
    "cancel": "Annuler"
    "sort_by": "triés par"
    "get_burnzone": "Laissez un commentaire et téléchargez gratuitement BurnZone"
    "oldest": " Le plus ancien"
    "newest": "Le plus récent"
    "points": " Points"
    "points_short": " pts"
    "answers": " Réponses"
    "votes": " Votes"
    "no_points": " {value} Points"
    "reply": " Répondre"
    "reply_in_challenge": " Répondre au défi"
    "comment_in_challenge": " Commenter le défi"
    "challenge": "Défi"
    "question": "Question"
    "key_point": " Point clé"
    "no_all_activities": " {value} Commentaire (s)"
    "no_comments": " {value} commentaire (s)"
    "no_challenges": " {value} défi (s)"
    "no_questions": " {value} question (s)"
    "no_answers": " {value} réponse (s)"
    "enter_your_pv": " Entrez votre point de vue ..."
    "vs": " vs"
    "enter_fb_uid": " Entrez le nom d'utilisateur Facebook ici"
    "non_verified_user": "L'adresse E-mail de cet utilisateur n'a pas été vérifiée"
    "logout": " Déconnexion"
    "gravatar_profile": " Profil sur Gravatar"
    "days_ago": "il y a {value} jour(s)"
    "hours_ago": "il y a {value} heure(s)"
    "minutes_ago": "il y a {value} minute(s)"
    "ends_in_days": " Termine dans {value} jour (s)"
    "ends_in_hours": " Termine dans {value} heures (s)"
    "ends_in_minutes": " Termine dans {value} minute (s)"
    "challenge_ended": " Challenge terminé"
    "ends_now": " Devrait se terminer d'une minute à l'autre"
    "just_now": "A l'instant"
    "exact_time": " sur {value}"
    "my_profile": " Mon profil"
    "challenge_comment": " Du point de vue du Challenger:"
    "original_comment": " Résumé du point mis en question:"
    "or_login_with": " ou connectez-vous avec"
    "flag": " Drapeau"
    "answer": " Réponse"
    "share": "Partage"
    "share_challenge": " Partager ce défi:"
    "share_conversation": " Partager cette conversation"
    "share_tw": " Partager sur Twitter"
    "share_fb": " Partager sur Facebook"
    "error_loading": "Nous n'avons pas pu charger cette conversation."
    "error_embed_sitenotexists": "Nom du site invalide."
    "error_embed_nourl": "URL de conversation invalide."
    "error_embed_embedlocalhost": " Vous ne pouvez pas insérer une conversation sur le site BurnZone."
    "error_embed_forceid": " Votre compte BurnZone est configuré pour forcer les identifiants de conversation, mais vous n'en avez indiqué aucun."
    "error_embed_useqs": " Votre compte BurnZone est configuré pour utiliser les touches de chaîne de requête, mais vous n'en avez pas enregistrées."
    "error_embed_url_not_reachable": " Votre article doit être accessible au public sur Internet."
    "flagged": "Marqué"
    "flagged_challenge": " Ce défi a été signalé"
    "change_image": " Définissez votre image"
    "change_your_data": " Modifier votre profil"
    "change_name": " Nom"
    "change_email": " E-mail"
    "change_submit": "Modification"
    "use_grav_image": " Gravatar"
    "use_fb_image": " Facebook"
    "error_access_api": "Un problème est survenu lors de votre demande"
    "user_banned": "Vous avez été exclu pour le moment"
    "create_comment_success": " Votre commentaire a été créé avec succès"
    "create_question_success": " Votre question a été créée avec succès"
    "create_answer_success": " Votre réponse a été créée avec succès"
    "create_comment_notallowed": "Vous ne pouvez pas commenter pour le moment"
    "create_comment_approval": " Votre commentaire doit être approuvé par un modérateur"
    "create_question_approval": " Votre question doit être approuvée par un modérateur"
    "create_answer_approval": " Votre réponse doit être approuvée par un modérateur"
    "create_challenge_success": " Votre défi a été créé avec succès"
    "create_challenge_notallowed": "Vous ne pouvez pas commenter pour le moment"
    "create_challenge_approval": " Votre défi doit être approuvée par un modérateur"
    "create_challenge_notpoints": " Vous n'avez pas assez de points pour répondre à ce commentaire"
    "create_challenge_denied": " Vous ne pouvez pas répondre à votre propre commentaire, à un commentaire qui n'existe pas, à un commentaire supprimé ou à un commentaire qui a été contesté (le défi pourrait ne pas être validé)"
    "vote_commentinch_user_in_challenge": " Vous ne pouvez pas voter car vous faites partie du défi"
    "vote_commentinch_once": " Vous ne pouvez voter qu'une seule fois et ne pouvez supprimer que votre dernier vote"
    "vote_ch_ended": " Vous ne pouvez pas voter pour un défi qui a pris fin"
    "like_comment_once": "vous ne pouvez aimer qu’une seule fois et ne pouvez retirer que votre derniere mention « j’aime » "
    "like_comment_retry": "Votre demande n'a pas été comprise. Veuillez la reformuler."
    "like_own_comment": "vous ne pouvez pas aimer votre commentaire"
    "like_author_unknown": " Quelqu'un"
    "needs_login": " Vous devez d'abord vous connecter"
    "needs_moderator": " Vous devez disposer des autorisations nécessaires pour cette"
    "user_exists": " Cette adresse E-mail est déjà utilisée par un autre utilisateur. Veuillez en indiquer une autre."
    "edit_profile": " Vous pouvez modifier votre nom et votre Avatar à partir de votre page de profil"
    "delete": "Supprimer"
    "top_answer": "Meilleure réponse"
    "create_user": " Ou créer un utilisateur BurnZone"
    "create_user_expl": " Créer un utilisateur vous permettra de commenter, de voter et de faire partie du classement."
    "anon_name": " Nom"
    "anon_email": " E-mail"
    "anon_pass": " Mot de passe"
    "invalid_name": " Veuillez entrer un nom"
    "invalid_email": " Veuillez entrer une adresse E-mail valide"
    "invalid_password": " Veuillez entrer un mot de passe valide"
    "email_must_be_valid": " Doit être valide pour être vérifié"
    "site_leaderboard": " Classement du site"
    "conversation_leaderboard": "Classement de la conversation"
    "site_leaderboard_title": " Ces classements sont basés sur toutes les activités des utilisateurs sur l'ensemble du site"
    "conversation_leaderboard_title": " Ces classements sont basés sur l'activité de ce seul article"
    "how_to_points": " Comment puis-je obtenir des points?"
    "not_verified": " Votre adresse E-mail n'est pas vérifiée. Vous n'êtes pas autorisé à signaler du  contenu inapproprié et ne pouvez voter qu' un certain nombre de fois."
    "no_password": "Vous n'avez pas encore créé de mot de passe et risquez de perdre votre compte. <a href=\"#{"#profile"}\"> Accédez à votre profil </a> puis cliquez sur \" Changer de mot de passe \" pour définir un mot de passe pour votre compte."
    "change_pass": " <a href=\"{url}/profile\" target=\"_blank\"> Changer le mot de passe </a>."
    "change_notifications": " <a href=\"{url}/profile\" target=\"_blank\"> Modifier les options de notification </a>."
    "subscription_options": " Options d'abonnement"
    "subscribe": "S'inscrire"
    "subscribe_own": " Abonnez-vous à mon contenu"
    "subscribe_auto": " S'auto-abonner aux conversations auxquelles ,je participe"
    "subscribe_conversations": " Abonnez-vous aux nouveaux articles"
    "subscribe_updates": " Abonnez-vous aux mises à jour de cette conversation"
    "subscribe_success": "Vous vous êtes abonné avec succès!"
    "unsubscribe_success": "Vous avez résilié votre abonnement avec succès"
    "read_more": " (Lire la suite)"
    "read_less": " (Lire moins)"
    "show_more": " Voir plus"
    "delete_all": " Supprimer tout"
    "format_text": " Formatage du texte"
    "challenge_ad_text": "Vous n'êtes pas d'accord avec un commentaire?"
    "challenge_ad_text_2": "Répondez à un défi et gagnez des points!"
    "learn_more": " En savoir plus"
    "best_answer": " Meilleure réponse"
    "challenged_comment": " Commentaire contesté"
    "challenged_question": " Question contestée"
    "go_to_comments": " Retour aux commentaires"
    "is_question": "Ceci est une question"
    "comment_deleted": " Ce commentaire a été supprimé"
    "question_deleted": " Cette question a été supprimée"
    "answer_deleted": " Cette réponse a été supprimée"
    "challenge_deleted": " Ce défi a été supprimé"
    "said": " dit"
    "challenged": " contesté"
    "challenge_winner": "Challenger gagnant"
    "title_like_up": "Aimer ce commentaire"
    "title_like_down": " Je n'aime pas ce commentaire"
    "title_best_answer": " Cette réponse est la meilleure, en fonction des votes reçus"
    "title_challenged": " Ce commentaire a été contesté"
    "title_reply": " Répondre à ce commentaire"
    "title_challenge": " Défier ce commentaire et apporter une réponse opposée"
    "title_share": " Partagez-le sur les médias sociaux"
    "title_flag": " Signaler comme Spam"
    "title_vote_up": "Vote positif"
    "title_vote_down": "Rétracter votre vote"
    "title_challenged_side": " Voici le commen,taire remis en question. Votez si vous êtes d'accord avec l'intervenant."
    "title_challenger_side": " Voici l'opinion de l'adversaire. Votez si vous êtes d'accord avec son point de vuee."
    "title_reply_comment": " Réagir à cet avis"
    "title_reply_question": " Commenter cette question"
    "title_reply_answer": " Commenter cette réponse"
    "title_reply_challenge": " Commenter ce défi"
    "title_question_answer": " Répondre à cette question"
    "title_answer_note": " Ceci est une réponse à la question ci-dessus"
    "title_is_question": " Cochez cette case si vous postez une question"
    "title_logo": " Commentaire de BurnZone"
    "new_notifications": " {value}"
    "user_notif_NEW_CONVERSATION": "un nouvel article a été publié sur {sitename}"
    "user_notif_WIN_QUESTION": " Vous avez eu la meilleure réponse!"
    "user_notif_WIN_QUESTION_here": " Vous avez eu la meilleure réponse!"
    "user_notif_NEW_COMMENT": " Nouveau commentaire"
    "user_notif_NEW_COMMENT_here": " Nouveau commentaire"
    "user_notif_ANSWER": " {username} répondu à votre commentaire"
    "user_notif_ANSWER_here": "{username} a répondu à votre commentaire"
    "user_notif_REPLY": "{username} a répondu à votre commentaire"
    "user_notif_REPLY_here": "{username} a répondu à votre commentaire"
    "user_notif_CHALLENGED": "{username} a répondu à votre commentaire"
    "user_notif_CHALLENGED_here": "{username} a répondu à votre commentaire"
    "user_notif_NEW_CHALLENGE": " Nouveau défi"
    "user_notif_NEW_CHALLENGE_here": " Nouveau défi"
    "user_notif_WIN_CHALLENGE": " Vous avez gagné votre défi!"
    "user_notif_WIN_CHALLENGE_here": " Vous avez gagné votre défi!"
    "user_notif_LOSE_CHALLENGE": " Vous avez perdu votre défi!"
    "user_notif_LOSE_CHALLENGE_here": " Vous avez perdu votre défi!"
    "user_notif_VOTE": " {username} ayant voté dans un défi"
    "user_notif_VOTE_here": " {username} ayant voté dans un défi"
    "user_notif_VOTE_down": "une personne a annulé son vote pour vous dans un défi"
    "user_notif_VOTE_down_here": "une personne a annulé son vote pour vous dans un défi"
    "user_notif_LIKE_ANSWER": "{username} a aimé votre réponse"
    "competitions": "Compétitions"
    "competition_banner": "La compétition: <strong> {title} </strong> de {start} et {end}; lire la <a target='_blank' href='{rules}'> règles </a> et participer à la conversation </a> "
    "competition_header": "<i class='icon-trophy'> </i> Gagnez <a href='{prize_url}'> {prize} </a> en rejoignant la {community} communauté et de commenter entre {start} - {end} (<span class='countdown'> {countdown}  </span> restante, voir <a target='_blank' href='{rules}'> règles </a>) "
    "competition_starts_on": "La compétition commence"
    "competition_active": "La compétition est active"
    "competition_ended_on": "La compétition a pris fin le"
    "competition_active_until": "La compétition sera active jusqu'à ce que"
    "competition_winner": "Gagnant"
    "competition_rules": "Règles"
    "competition_prize": "Prix"
    "competition_ranking_title": "Classement de la compétition"
    "user_notif_COMPETITION_START": "La compétition a commencé: {title}"
    "user_notif_COMPETITION_STARTING": "{days} jours jusqu'au début de la compétition: {title}"
    "user_notif_COMPETITION_END": "La compétition s'est terminée: {title}"
    "user_notif_COMPETITION_ENDING": "La compétition {title} se termine dans {days} jours"
    "submit_comment": "Soumettre un commentaire"
    "submit_question": "Soumettre une question"
    "reg_and_submit_comment": "Enregistrer"
}
