module.exports = {
  name: "日本語 (にほんご)"
  code: "ja"
  terms:
    "browser_support": " Burnzoneはお使いのブラウザではサポートされていません。最新バージョンのブラウザにアップグレードするか、MozillaまたはChromeをご利用ください。"
    "login_to_comment": " コメントを投稿するにはログインをしてください"
    "login_to_challenge": "ログインして挑戦"
    "login_with": "ログイン"
    "signup_with": "新規登録"
    "sign_in": " サインイン"
    "sign_in_using": " 使用してサインイン"
    "settings": "[設定]"
    "or": " または"
    "comment": " コメント"
    "comments": " コメント"
    "challenges": "挑戦"
    "questions": " 質問"
    "likes": "いいね"
    "write_comment": "ご意見やご感想を共有..."
    "write_answer": " ここに答えを入力してください"
    "answered": " 答え"
    "submit": "送信"
    "cancel": " キャンセル"
    "sort_by": "並び順"
    "get_burnzone": " BurnZoneからのコメントを取得"
    "oldest": "最古"
    "newest": " 最新"
    "points": "ポイント"
    "points_short": "ポイント"
    "answers": "答え"
    "votes": " 投票"
    "no_points": "{value} ポイント"
    "reply": " 返信"
    "reply_in_challenge": "この挑戦に返信する"
    "comment_in_challenge": "この挑戦にコメントする"
    "challenge": " 挑戦"
    "question": "質問"
    "key_point": " キーポイント"
    "no_all_activities": "{value} コメント"
    "no_comments": "{value} コメント"
    "no_challenges": "{value}挑戦"
    "no_questions": "{value} 質問"
    "no_answers": "{value}答え"
    "enter_your_pv": " あなたの考えを入力してください..."
    "vs": " 対"
    "enter_fb_uid": " ここにFacebookのユーザーIDを入力してください"
    "non_verified_user": "このユーザーのメールアドレスは認証されていません"
    "logout": " ログアウト"
    "gravatar_profile": "Gravatar上のプロフィール"
    "days_ago": "{value}日前"
    "hours_ago": "{value}時間前"
    "minutes_ago": "{value}分前"
    "ends_in_days": "{value}日で終了"
    "ends_in_hours": "{value}時間で終了"
    "ends_in_minutes": "{value}分で終了"
    "challenge_ended": " 終了"
    "ends_now": "いつでも終了します"
    "just_now": " ちょうど今"
    "exact_time": "{value}に"
    "my_profile": "プロフィール"
    "challenge_comment": "挑戦者の視点："
    "original_comment": " 挑戦ポイントの合計："
    "or_login_with": " またはログイン"
    "flag": " フラグ"
    "answer": " 答え"
    "share": "共有"
    "share_challenge": " この挑戦を共有する："
    "share_conversation": " この会話を共有する"
    "share_tw": " Twitterで共有"
    "share_fb": " Facebookで共有"
    "error_loading": "この会話を読み込むことができませんでした"
    "error_embed_sitenotexists": " 無効なサイト名"
    "error_embed_nourl": " 無効な会話のURL"
    "error_embed_embedlocalhost": " BurnZoneサイト上に会話を入力することができませんでした"
    "error_embed_forceid": "あなたのBurnZoneアカウントは強制的に会話用のIDによって設定されていますが、あなたはひとつも提供していません。"
    "error_embed_useqs": "BurnZoneアカウントは質問にもとづいて設定されていますが、あなたはすべての質問を提供していません。"
    "error_embed_url_not_reachable": " あなたの記事は、インターネット上にて一般公開可能でなければなりません"
    "flagged": " フラグ"
    "flagged_challenge": " この挑戦にはフラグが設定されています"
    "change_image": "写真を設定する"
    "change_your_data": "プロフィールの変更"
    "change_name": " 名前"
    "change_email": " Eメール"
    "change_submit": " 変更"
    "use_grav_image": " Gravatar"
    "use_fb_image": "Facebook"
    "error_access_api": " リクエストの処理中に問題が発生しました"
    "user_banned": "禁止されています"
    "create_comment_success": "コメントは正常に作成されています"
    "create_question_success": " 質問は正常に作成されています"
    "create_answer_success": "答えは正常に作成されています"
    "create_comment_notallowed": "現在あなたはコメントするのを禁止されています"
    "create_comment_approval": "コメントは議長の承認待ちです"
    "create_question_approval": "質問は議長の承認待ちです"
    "create_answer_approval": "答えは議長の承認待ちです"
    "create_challenge_success": "秘密の質問は、正常に作成されています"
    "create_challenge_notallowed": "現在あなたは挑戦的なコメントをするのを禁止されています"
    "create_challenge_approval": " あなたの挑戦は、議長の承認を待っています"
    "create_challenge_notpoints": " このコメントに挑戦するにはポイントが足りません"
    "create_challenge_denied": "自身のコメントや存在しないコメント、削除されたコメント、または以前に挑戦されたことのないコメント（未承認の挑戦）には挑戦できません。"
    "vote_commentinch_user_in_challenge": " 挑戦している間は投票できません"
    "vote_commentinch_once": "一度だけ投票することができます。また直近の投票だけを取り消すことができます"
    "vote_ch_ended": "終了した挑戦には投票できません"
    "like_comment_once": "一度だけいいねができます。また直近にしたいいねのみ取り消すことができます"
    "like_comment_retry": " あなたの要求に矛盾がありました。再試行してください。"
    "like_own_comment": "あなた自身のコメントにいいねはできません"
    "like_author_unknown": " 誰か"
    "needs_login": "最初にログインする必要があります"
    "needs_moderator": "議長の承認が必要です"
    "user_exists": " このメールアドレスは、すでに他のユーザーによって使用されます。別のメールアドレスをご利用ください。"
    "edit_profile": "プロフィールページから名前とアバターを変更することができます。"
    "delete": " 削除"
    "top_answer": "最初の回答"
    "create_user": " またはBurnZoneユーザーアカウントを作成"
    "create_user_expl": " ユーザーアカウントを作成すると、コメントを投票し、リーダーボードに参加できるようになります"
    "anon_name": " 名前"
    "anon_email": " Eメール"
    "anon_pass": " パスワード"
    "invalid_name": " 名前を入力してください"
    "invalid_email": " 有効なメールアドレスを入力してください"
    "invalid_password": " 有効なパスワードを入力してください"
    "email_must_be_valid": "認証には有効でなければなりません"
    "site_leaderboard": "サイト リーダーボード"
    "conversation_leaderboard": " 会話リーダーボード"
    "site_leaderboard_title": "これらのランキングは、ユーザーのサイト全体での活動に基づいています"
    "conversation_leaderboard_title": "これらのランキングは、この単一の記事での活動に基づいています"
    "how_to_points": " どうすればポイントを得ることができますか"
    "not_verified": " あなたのメールアドレスは認証されていません。不適切な内容にはフラグをたてることができません。また、限られた回数しか投票できません"
    "no_password": "パスワードを設定しないと、アカウントを失う恐れがあります。<a href=\"#{"#profile"}\">プロフィールに移動</a>クリック \"パスワード変更\" アカウントにパスワードを設定するには"
    "change_pass": "<a href=\"{url}/profile\" target=\"_blank\">パスワード変更</a>."
    "change_notifications": "<a href=\"{url}/profile\" target=\"_blank\">オプション通知を変更</a>."
    "subscription_options": " 購読オプション"
    "subscribe": " 購読する"
    "subscribe_own": " 自分の著作物を購読する"
    "subscribe_auto": "参加する会話を自動購読する"
    "subscribe_conversations": " 新しい記事を購読する"
    "subscribe_updates": "更新された会話を購読する"
    "subscribe_success": "購読を開始いたしました"
    "unsubscribe_success": "購読解除しました"
    "read_more": " （続きを読む）"
    "read_less": " （続きを隠す）"
    "show_more": " さらに表示"
    "delete_all": " すべて削除"
    "format_text": " テキストの書式設定"
    "challenge_ad_text": " コメントに同意しなくてよいですか？"
    "challenge_ad_text_2": "挑戦してポイントを獲得"
    "learn_more": " 詳細はこちら"
    "best_answer": " ベストアンサー"
    "challenged_comment": " コメントに挑戦"
    "challenged_question": " 質問に挑戦"
    "go_to_comments": " コメントに戻る"
    "is_question": " これは質問です"
    "comment_deleted": " このコメントは削除されました"
    "question_deleted": " この質問を削除しました"
    "answer_deleted": " この回答は削除されました"
    "challenge_deleted": " この挑戦は削除されました"
    "said": "といいました"
    "challenged": " 挑戦"
    "challenge_winner": "この挑戦の勝者"
    "title_like_up": "このコメントにいいねする"
    "title_like_down": "このコメントにがっかりする"
    "title_best_answer": "これは投票のなかで最高の答えです"
    "title_challenged": "このコメントは挑戦されました"
    "title_reply": " このコメントに返信"
    "title_challenge": " 反対意見を公開するためにこのコメントに挑戦します"
    "title_share": " ソーシャルメディア上で共有します"
    "title_flag": " スパム報告"
    "title_vote_up": " 投票する"
    "title_vote_down": " 投票を撤回"
    "title_challenged_side": "コメントに挑戦されました。同意の場合はこのコメントした人に投票しましょう"
    "title_challenger_side": " これは挑戦者の意見です。もしこの反対意見に同意するのであれば投票しましょう"
    "title_reply_comment": " この意見にコメントする"
    "title_reply_question": " この質問へのコメント"
    "title_reply_answer": " この回答のコメント"
    "title_reply_challenge": "この挑戦にコメントする"
    "title_question_answer": " この質問に答える"
    "title_answer_note": " これは、上記の質問への回答です"
    "title_is_question": "質問を投稿している場合、ここをチェックする"
    "title_logo": "BurnZoneのコメント"
    "new_notifications": "{value}"
    "user_notif_NEW_CONVERSATION": " 新しい記事は {sitename}に掲載されました"
    "user_notif_WIN_QUESTION": "いい回答です!"
    "user_notif_WIN_QUESTION_here": "いい回答です!"
    "user_notif_NEW_COMMENT": " 新しいコメント"
    "user_notif_NEW_COMMENT_here": " 新しいコメント"
    "user_notif_ANSWER": "{username}はあなたのコメントに回答しました"
    "user_notif_ANSWER_here": "{username}はあなたのコメントに回答しました"
    "user_notif_REPLY": "{username}はあなたのコメントに返答しました"
    "user_notif_REPLY_here": "{username}はあなたのコメントに返答しました"
    "user_notif_CHALLENGED": "{username}はあなたのコメントに挑戦しました"
    "user_notif_CHALLENGED_here": "{username}はあなたのコメントに挑戦しました"
    "user_notif_NEW_CHALLENGE": " 新たな挑戦"
    "user_notif_NEW_CHALLENGE_here": " 新たな挑戦"
    "user_notif_WIN_CHALLENGE": "挑戦に勝利しました!"
    "user_notif_WIN_CHALLENGE_here": "挑戦に勝利しました!"
    "user_notif_LOSE_CHALLENGE": "挑戦に敗北しました!"
    "user_notif_LOSE_CHALLENGE_here": "挑戦に敗北しました!"
    "user_notif_VOTE": "{username}はあなたの挑戦に投票しました"
    "user_notif_VOTE_here": "{username}はあなたの挑戦に投票しました"
    "user_notif_VOTE_down": " 誰かがあなたへの挑戦に投票したのを取り消しました"
    "user_notif_VOTE_down_here": " 誰かがあなたへの挑戦に投票したのを取り消しました"
    "user_notif_LIKE_ANSWER": "{username}は回答にいいねしました"
    "competitions": "大会"
    "competition_banner": "大会: <strong>{title}</strong> from {start} to {end}; read the <a target='_blank' href='{rules}'>Rules</a> and join the conversation!</a>"
    "competition_header": "<i class='icon-trophy'></i> Win <a href='{prize_url}'>{prize}</a> by joining the {community} community and commenting between {start} - {end} (<span class='countdown'>{countdown}</span> remaining, see <a target='_blank' href='{rules}'>rules</a>)"
    "competition_starts_on": "競争は上の始まり"
    "competition_active": "競争がアクティブになっている"
    "competition_ended_on": "競争は日に終了した "
    "competition_active_until": "競争がアクティブになるまで"
    "competition_winner": "勝者"
    "competition_rules": "ルール"
    "competition_prize": "賞"
    "competition_ranking_title": "競争はランキング "
    "user_notif_COMPETITION_START": "競争が開始しました：{title} "
    "user_notif_COMPETITION_STARTING": "{days}競争が始まるまで{title}日"
    "user_notif_COMPETITION_END": "競争は終わった：{title} "
    "user_notif_COMPETITION_ENDING": "競争{title} {days}日で終わる "
    "submit_comment": "コメント送信 "
    "submit_question": "質問を送信」"
    "reg_and_submit_comment": "登録"
}
