module.exports = {
  name: "English"
  code: "en"
  terms:
    "browser_support": "Burnzone is not supported in your browser. Please upgrade your browser to the latest version or change your browser to Mozilla or Chrome."
    "view_separate_page": "Problems on mobile devices? <br> View BurnZone in a separate page."
    "create_comment_thread": "Comment in this thread"
    "login": "Login"
    "login_to_comment": "Login to comment"
    "login_to_challenge": "Login to challenge"
    "login_with": "Login with"
    "signup_with": "Signup with"
    "sign_in": "Sign in"
    "sign_up": "Sign up"
    "sign_in_using": "Sign in using"
    "sign_in_already_have_account": "Already registered? <a>Sign in</a>."
    "settings": "My Settings"
    "or": "or"
    "forum-time": "Time passed since the last activity in this topic"
    "time": "Time"
    "comment": "Comment"
    "comments": "Comments"
    "challenges": "Challenges"
    "questions": "Questions"
    "likes": "likes"
    "write_forum_title": "Start a new forum thread"
    "write_comment": "Voice your thoughts here..."
    "write_answer": "Enter your answer here"
    "start_commenting": "Start commenting"
    "start_replying": "Start replying"
    "start_challenging": "Start challenging"
    "title_edit_comment": "Edit your comment"
    "answered": "answered"
    "submit": "Submit"
    "forum_new_thread": "Create T"
    "forum_new_thread_large": "Create Thread"
    "start_conversation": "Start a conversation"
    "forum_mark_private": "Mark as private"
    "forum_private_for_guest": "This is a private thread. Login and a moderator could grant access."
    "forum_private_for_you": "This is a private thread. Only a moderator can grant access."
    "forum_is_private": "PRIVATE"
    "forum_is_private_short": "P"
    "forum_private_title": "Makes thread visible only to moderators and users with private access."
    "edit_comment": "Edit"
    "edit_comment_save": "Save"
    "edit_comment_cancel": "Cancel"
    "reg_and_submit_comment": "Register"
    "cancel": "Cancel"
    "sort_by": "Sorted by"
    "get_burnzone": "Get BurnZone Commenting"
    "oldest": "Oldest"
    "newest": "Newest"
    "sort_activity_rating": "Most activity"
    "sort_activity_rating_down": "Most activity"
    "sort_activity_rating_up": "Least activity"
    "sort_latest_activity": "Latest activity"
    "sort_latest_activity_down": "Latest activity"
    "sort_latest_activity_up": "Oldest activity"
    "sort_comments": "Comments"
    "sort_comments_down": "Most comments"
    "sort_comments_up": "Least comments"
    "sorting_options": "You can sort threads by the number of comments, last activity, or most active"
    "filter_all": "All"
    "filter_best": "Best"
    "bets_filter_all": "All"
    "bets_filter_open": "Open"
    "bets_filter_closed": "Closed"
    "bets_filter_ended": "Pending"
    "bets_filter_resolved": "Resolved"
    "bets_thread_title": "All Yolos"
    "bets_thread_info": "View users risking their Reputation Points as 'Yolos'"
    "rank": "Rank"
    "badge_cutoff": "Cutoff for badge:"
    "nobody_has_points": "Nobody has enough points to qualify on this leaderboard."
    "points": "Points"
    "points_short": "pts"
    "answers": "Answers"
    "votes": "Votes"
    "no_points": "{value} Points"
    "reply": "Reply"
    "reply_with_bet": "Yolo"
    "replied_to": "replied to {value}"
    "replied_to_challenge": "replied in challenge"
    "reply_in_challenge": "Reply in the challenge"
    "view_original": "See original comment"
    "comment_in_challenge": "Comment in the challenge"
    "more_actions": "More Actions"
    "challenge": "Challenge"
    "challenge_symbol": "C"
    "question":"Question"
    "question_symbol": "?"
    "submit_bet_title": "Propose a wager to specific users or the community &#013;and risk winning or losing points."
    "title_bet_summary": "A summary of the amount of points you are risking and the amount of total points needed by users to accept the Yolo."
    "bet_start_forf": "Resolution"
    "title_bet_start_forf": "Start resolution"
    "bet_close": "Close Yolo"
    "title_bet_close": "Close the Yolo so that users will not be able to accept the opposite view of your Yolo anymore"
    "bet_pts_max_user": "Max pts/user"
    "title_bet_pts_max_user": "Maximum amount of points a user is allowed to accept. Use this to prevent a user from taking all available points. Leave the field blank if you don't want to impose a limit."
    "bet_summary": "Summary"
    "bet_closed": "Yolo Closed"
    "bet_closed_forf_starts": "Ends in {time}"
    "bet_forf_ends": "for {time}"
    "bet_closed_title": "Yolo Closed."
    "bet_forf": "Yolo Resolution"
    "bet_forf_title": "Users can acknowledge loss"
    "bet_forf_mod": "Moderator Resolution"
    "bet_forf_mod_title": "The Yolo has been sent to moderator for resolution"
    "bet_forf_closed": "Yolo Resolution Closed"
    "bet_forf_closed_title": "Resolution window closed"
    "bet_undecided": "Undecided"
    "bet_undecided_title": "Moderator can choose winning side"
    "bet_tie": "Yolo is Tie"
    "bet_tie_title": "Nobody has won and users get their points back"
    "bet_rolledback": "Yolo Rolledback"
    "bet_rolledback_title": "Nobody accepted Yolo and author gets his points back"
    "bet_offer": "Yolo Offer:"
    "bet_open": "Yolo"
    "bet_open_title": "Users can join yolo"
    "bet_resolved": "Yolo Resolved"
    "want-bet": "Submit a Yolo"
    "bet_describe": "Describe Yolo"
    "title_bet_users": "Specify the user(s) you want to target by typing their username."
    "bet_target": "Who"
    "title_bet_start_forf_date": "Specify the date when the outcome of the Yolo will be known and a winning side can be determined. If the date is unknown, place a date far enough in the future and you will be able to manually end the Yolo."
    "bet_end_date": "Close Date"
    "bet_start_forf_date": "Resolution Date"
    "title_bet_description": "Describe in detail the specifications of the wager you are proposing."
    "title_bet_end_date": "Specify the last date a user can accept the opposite view of your yolo. If the date is unknown, place a date far enough in the future and you will be able to manually close accepting the Yolo."
    "title_bet_points_offered": "This is the amount of points that you are willing to risk in the Yolo."
    "bet_points_offered": "Points Offered"
    "bet_pts_available": "Available:"
    "bet_pts_unaccepted": "Unaccepted:"
    "bet_accept_min_pts": "Min"
    "bet_accept_max_pts": "Max"
    "bet_win_pts": "Win"
    "bet_won_pts": "Won {value} pts"
    "bet_lost_pts": "Lost {value} pts"
    "title_bet_odds_label": "Odds represent the ratio between the amounts staked by parties to a wager."
    "bet_odds_label": "Odds"
    "bet_point_ratio_joined": ""
    "bet_point_ratio_accepted": "to"
    "bet_view_odds_label": "Odds:"
    "title_bet_type": "Targeting allows you to reserve points for users that you want to participate in your Yolo. Open allows any user to accept the yolo and take the opposing side."
    "bet_type_targeted_open": "Targeted and Open"
    "bet_type_targeted_closed": "Targeted Closed"
    "bet_type_open": "Open"
    "bet_type": "Yolo Type"
    "bet_points_accepted": "Risk: "
    "bet_accept": "Accept Yolo"
    "bet_decline": "Decline Yolo"
    "bet_points_risked": "Pts Risked:"
    "bet_points_win": "Pts to Win:"
    "bet_explain_minimum": "Yolos require you to offer at least {points} points"
    "bet_explain_targeted": "Targeted Yolos require you to offer at least {points} points per user"
    "accepted_users": "Accepted users"
    "declined_users": "Declined users"
    "forfeited_users": "Users who acknowledged loss"
    "bet_forfeit": "Lost Yolo"
    "bet_claim": "Won Yolo"
    "resolve_bet_side": "Pick Yolo winner"
    "resolve_joined": "Author"
    "resolve_accepted": "Users who accepted"
    "resolve_tie": "Tie (nobody wins)"
    "pending_users": "Pending users"
    "joined_users": "Joined users"
    "won": "Won"
    "promoted": "Promoted"
    "promoted_title": "Promoted"
    "promoted_title_by": "User {user} promoted this comment"
    "promoted_symbol": "P"
    "promote": "Promote"
    "moderate": "Moderate"
    "promote_points": "Promote with"
    "add_points": "Add"
    "promote_title": "Promoting will make this comment appear as the top comment to all users"
    "promoted_points_note": "Promoted for {value} pts"
    "promoted_by_moderator_note": "Promoted by moderator"
    "current_promote_points": "This comment already has {value} points towards promotion."
    "promote_points_needed": "Add at least {value} more points to promote."
    "promote_points_needed_newcomment": "Add at least {value} points to promote."
    "below_minimum_promote_points": "You must offer more points for your comment to be promoted"
    "self_promote": "Promote"
    "demote": "Demote"
    "demote_title": "Demoting will make this comment no longer appear at the top"
    "key_point": "Key point"
    "stripe_btn_label_fund_comment": "Ignite for {{amount}}"
    "stripe_desc_fund_comment": "Ignite this comment to mark it as influential and give benefits to the author"
    "no_all_activities": "{value} Comment(s)"
    "no_comments": "{value} comment(s)"
    "no_forum_new_comments": "new"
    "no_conversations": "{value} conversation(s)"
    "no_challenges": "{value} challenge(s)"
    "no_questions": "{value} question(s)"
    "no_bets": "{value} Yolo(s)"
    "no_answers": "{value} answer(s)"
    "trusted_comments_required": "You have {value} comments. At least {req_comments} comments are required for the Trusted badge."
    "trusted_vote_ratio": "You have {upvotes} upvotes and {downvotes} downvotes, a ratio of {ratio}:1. A ratio of {req_ratio}:1 is required for the Trusted badge."
    "trusted_social_verified": "You are verified on {sites}. Verification on at least {req_count} site(s) is required for the Trusted badge."
    "trusted_social_noverified": "You are not verified on any social media site. Verification on at least {req_count} site(s) is required for the Trusted badge (click <a href='http://help.theburn-zone.com/customer/portal/articles/2166918' target='_blank'>here</a> for help)."
    "trusted_profile_age": "You are on this site since {since} ({age} days). At least {req_age} days are required for the Trusted badge."
    "profile_age": "Profile Age"
    "enter_your_pv": "Enter your point of view..."
    "vs": "vs"
    "enter_fb_uid": "Enter Facebook user id here"
    "non_verified_user":"The email address of this user has not been verified"
    "verified": "verified"
    "logout": "Logout"
    "gravatar_profile": "Profile on Gravatar"
    "edited_days_short": "edited {value} d ago"
    "edited_hours_short": "edited {value} h ago"
    "edited_minutes_short": "edited {value} m ago"
    "edited_just_now_short": "edited just now"
    "days_short": "{value} d"
    "hours_short": "{value} h"
    "minutes_short": "{value} m"
    "just_now_short": "0 m"
    "ends_in_days": "Ends in {value} day(s)"
    "ends_in_hours": "Ends in {value} hour(s)"
    "ends_in_minutes": "Ends in {value} minute(s)"
    "closes_in_days": "Closes in {value} day(s)"
    "closes_in_hours": "Closes in {value} hour(s)"
    "closes_in_minutes": "Closes in {value} minute(s)"
    "challenge_ended": "Ended"
    "ends_now": "Should end any minute now"
    "closes_now": "Should close any minute now"
    "exact_time": "on {value}"
    "my_profile": "My Public Profile"
    "challenge_comment": "Challenger's point of view:"
    "original_comment": "Summary of point challenged:"
    "or_login_with": "or login with"
    "flag": "Flag"
    "answer": "Answer"
    "share": "Share"
    "close": "close"
    "share_challenge": "Share this challenge: "
    "share_conversation": "Share this conversation"
    "share_tw": "Share on Twitter"
    "share_fb": "Share on Facebook"
    "share_mail": "Share by Email"
    "share_mail_subject": "I wanted to share this BurnZone comment with you"
    "share_mail_body": "You can find it here:"
    "error": "Error"

    "error_create_bet_invalid": "Invalid request"
    "error_create_bet_invalid_parent": "Invalid request"
    "error_create_bet_denied": "The parent comment has been deleted"
    "error_create_bet_notsupported": "This operation is not supported"
    "error_create_bet_invalid_profile": "Could not find your profile"
    "error_create_bet_needs_premium": "This action requires the premium package to be activated for this site"
    "error_create_bet_bet_invalid_type": "Invalid Yolo type"
    "error_create_bet_bet_invalid_points_value": "Invalid points value. Please offer at least the minimum amount of points, ensure that every targeted user can risk the minimum amount and if you configure maximum points per user, make sure that it is higher than the minimum amount."
    "error_create_bet_bet_invalid_ratio": "Invalid ratio value"
    "error_create_bet_bet_invalid_date": "Invalid date for closing the Yolo. The Yolo must end in the future and after the minimum Yolo period. This error might happen if a considerable amount of time has passed since you selected the date. Please select another date."
    "error_create_bet_bet_invalid_start_forf_date": "Invalid date for resolution. Resolution must start in the future and after the bet closes. This error might happen if a considerable amount of time has passed since you selected the date."
    "error_create_bet_bet_invalid_users": "Invalid users"
    "error_create_bet_bet_invalid_users_value": "Invalid targeted user"
    "error_create_bet_bet_cannot_target_self": "You cannot target yourself in a Yolo"
    "error_create_bet_bet_users_nonexistent": "Invalid targeted user"
    "error_create_bet_notallowed": "For the moment you have been banned from commenting"
    "error_create_bet_notenoughpoints": "You don't have enough points to perform that action"
    "error_create_bet_low_status": "You don't have the required status to start a new Yolo"
    "error_create_bet_invalid_text": "You must enter a description for your Yolo"
    "error_accept_bet_notexists": "The Yolo does not exist or it has been deleted"
    "error_accept_bet_denied": "The Yolo is not open or it doesn't allow accepts from non-targeted users"
    "error_accept_bet_user_is_author": "You can't accept your own Yolo"
    "error_accept_bet_invalid_points_value": "Invalid points value. Either you submitted an incorrect points value (please check the minimum and maximum allowed), or the Yolo might not have this number of points available. Please review the Yolo and retry if necessary"
    "error_accept_bet_conflict": "The Yolo conditions have changed. Either there are fewer points available than you requested, or the Yolo has been closed. Please review the Yolo and retry if necessary"
    "error_accept_bet_notenoughpoints": "You don't have enough points to accept this Yolo with this amount. Decrease the amount of points and try again"
    "error_accept_bet_needs_premium": "This action requires the premium package to be activated for this site"
    "error_decline_bet_notexists": "The Yolo does not exist or it has been deleted"
    "error_decline_bet_denied": "The Yolo is not open"
    "error_decline_bet_conflict": "The Yolo conditions have changed. The Yolo has been closed. Please review the Yolo"
    "error_decline_bet_needs_premium": "This action requires the premium package to be activated for this site"
    "error_forfeit_bet_notexists": "The Yolo does not exist or it has been deleted"
    "error_forfeit_bet_denied": "The Yolo is not in the resolution stage"
    "error_forfeit_bet_conflict": "The Yolo conditions have changed. Please review the Yolo data and retry"
    "error_forfeit_bet_needs_premium": "This action requires the premium package to be activated for this site"
    "error_claim_bet_notexists": "The Yolo does not exist or it has been deleted"
    "error_claim_bet_denied": "The Yolo is not in the resolution stage"
    "error_claim_bet_conflict": "The Yolo conditions have changed. Please review the Yolo data and retry"
    "error_claim_bet_needs_premium": "This action requires the premium package to be activated for this site"
    "error_resolve_bet_notexists": "The Yolo does not exist or it has been deleted"
    "error_resolve_bet_denied": "The Yolo is not in a state that requires manual resolving"
    "error_resolve_bet_conflict": "The Yolo has already been resolved. Please review the Yolo"
    "error_resolve_bet_needs_premium": "This action requires the premium package to be activated for this site"
    "error_end_bet_invalid": "The Yolo is not open. Please check the Yolo status"
    "error_end_bet_conflict": "The Yolo has been already closed. Please check the Yolo status"
    "error_end_bet_needs_author": "Only bet authors can manually close the bet"
    "error_start_forf_bet_invalid": "The Yolo is not closed. Please check the Yolo status"
    "error_start_forf_bet_conflict": "The Yolo is already in the resolution stage. Please check the Yolo status"
    "error_start_forf_bet_needs_author": "Only bet authors can manually advance to resolution"

    "error_loading": "We were not able to load this conversation."
    "error_create_comment_invalid_text": "You must enter a text for the comment"
    "error_create_challenge_invalid_text": "You must enter a text for the challenge"
    "error_create_context_invalid_text": "You must enter a title and a content for the thread"
    "error_edit_comment_notexists": "This comment does not exist or it is not approved"
    "error_edit_comment_notallowed": "You are not allowed to edit this comment"
    "error_edit_comment_notsupported": "This operation is not supported"
    "error_edit_comment_invalid_text": "Please enter a text"
    "error_embed_sitenotexists": "Invalid site name."
    "error_embed_nourl": "Invalid conversation URL."
    "error_embed_embedlocalhost": "Cannot embed a conversation on the BurnZone site."
    "error_embed_forceid": "Your BurnZone account is configured to force conversation IDs but you did not provide one."
    "error_embed_useqs": "Your BurnZone account is configured to use query string keys but you did not provide all of them."
    "error_embed_url_not_reachable": "Your article must be publicly accessible on the internet."
    "error_embed_siterequired": "The site name is not configured."
    "error_embed_forum_not_enabled": "Forums are not enabled."

    "notenoughpoints": "You don't have enough points to perform that action"
    "error_share_fb": "There was an error sharing on Facebook: {error}"
    "info_share_fb": "Successfully shared on Facebook: {text}"
    "error_share_tw": "There was an error sharing on Twitter: {error}"
    "info_share_tw": "Successfully shared on Twitter: {text}"
    "started": "Started"
    "flagged": "Flagged"
    "flagged_challenge": "This challenge has been flagged"
    "change_image": "Set your image"
    "change_your_data": "Change your profile data"
    "change_name": "Name"
    "change_email": "Email"
    "change_submit": "Change"
    "use_grav_image": "Gravatar"
    "use_fb_image": "Facebook"
    "error_access_api": "There was a problem while handling your request"
    "success_api": "OK"
    "user_banned": "You have been banned for the moment"
    "end_bet_success": "The Yolo has been closed"
    "accept_bet_success": "You have accepted the Yolo"
    "decline_bet_success": "You have declined the Yolo"
    "forfeit_bet_success": "You have acknowledged loss in the Yolo"
    "claim_bet_success": "You've claimed you've won. The other participants will still need to admit they lost."
    "resolve_bet_success": "The Yolo has been resolved. It will take a while until the points are calculated"
    "start_forf_bet_success": "The Yolo is now in the resolution stage"
    "create_context_success": "Your forum topic has been successfully created"
    "create_context_approval": "Your forum topic awaits moderator approval"
    "create_comment_success": "Your comment has been successfully created"
    "create_question_success": "Your question has been successfully created"
    "create_answer_success": "Your answer has been successfully created"
    "create_comment_notallowed": "For the moment you have been banned from commenting"
    "create_comment_approval": "Your comment awaits moderator approval"
    "create_question_approval": "Your question awaits moderator approval"
    "create_answer_approval": "Your answer awaits moderator approval"
    "create_challenge_success": "Your challenge has been successfully created"
    "create_challenge_notallowed": "For the moment you have been banned from challenging comments"
    "create_challenge_approval": "Your challenge awaits moderator approval"
    "create_challenge_notpoints": "You don't have enough points to challenge this comment"
    "create_challenge_denied": "You can't challenge your own comment, a comment that does not exists, a deleted comment or a comment that has been challenged before (the challenge could be unapproved)"
    "create_low_status": "You don't have the required status to post a comment"
    "context_create_low_status": "You don't have the required status to start a new forum thread"
    "vote_low_status": "You don't have the required status to vote"
    "like_low_status": "You don't have the required status to like"
    "flag_low_status": "You don't have the required status to flag"
    "vote_commentinch_user_in_challenge": "You can't vote because you are in the challenge"
    "vote_commentinch_once": "You can vote only once and you can retract only your previous vote"
    "vote_ch_ended": "You can't vote in a challenge that has ended"
    "like_comment_once": "You can like only once and you can retract only your previous like"
    "like_comment_retry": "There was a conflict in your request. Please retry."
    "like_comment_not_verified": "You must be verified."
    "like_comment_needs_login": "You must be logged in."
    "like_own_comment": "You cannot like your own comment"
    "like_active_competition": "You cannot dislike a comment while you participate in a competition."
    "like_author_unknown": "Someone"
    "ignite_author_unknown": "Someone"
    "needs_login": "You have to log in first"
    "needs_moderator": "You need moderator permissions for this"
    "needs_premium": "This action requires the premium package to be activated for this site"
    "user_exists": "This email address is already used by another user. Please try another one."
    "edit_profile": "You can change your name and avatar from <a href=\"{url}/profile\" target=\"_blank\">your profile page</a>"
    "delete": "Delete"
    "delete_with_points": "Delete &amp; -20pts"
    "confirm_delete_challenge": "Are you sure you want to delete this challenge?"
    "confirm_delete_challenge_wpts": "Are you sure you want to delete this challenge and remove 20 points from user '{username}'?"
    "confirm_delete_comment": "Are you sure you want to delete this comment?"
    "confirm_delete_comment_wpts": "Are you sure you want to delete this comment and remove 20 points from user '{username}'?"
    "show_in_forum": "Show in forum"
    "show_in_forum_title": "Unchecking this box will remove the thread from the forum"
    "private_thread_title": "Checking this box will make the thread private"
    "top_answer": "Top answer"
    "social_icon_login": "If you already have a BurnZone account, click the BZ icon."
    "create_user": "Or create a BurnZone user if you haven't already signed up."
    "create_user_expl": "Creating a user will allow you to comment, vote and be part of the leaderboard."
    "challenge_cost_help": "Creating a challenge costs you profile points but you get more if you win the challenge. Only the first challenge is free."
    "anon_name": "Name"
    "anon_email": "Email"
    "anon_pass": "Password (optional)"
    "invalid_name": "Please input a name"
    "invalid_email": "Please input a valid email address"
    "invalid_password": "Please input a valid password"
    "invalid_points_value": "Please input a non-negative integer for the amount of points you are offering"
    "email_must_be_valid": "Must be valid to verify"
    "password_is_optional": "You can choose a password later"
    "leaderboards_title": "Leaderboards"
    "site_leaderboard": "Site"
    "top_users": "Top new users"
    "users" : "Users"
    "conversation_leaderboard": "Conversation"
    "site_leaderboard_title": "These rankings are based on all the activities users have on the entire site"
    "conversation_leaderboard_title": "These rankings are based on the activity on this single article"
    "scroll_leaderboard_top": "Show top users in the leaderboard"
    "scroll_leaderboard_up": "Show users higher in the leaderboard"
    "scroll_leaderboard_down": "Show users lower in the leaderboard"
    "how_to_points": "Learn how to earn points"
    "not_verified": "Your email address is not verified. You are not allowed to flag inappropriate content and you can vote for a limited number of times."
    "not_verified_marker": "Not verified"
    "notenoughpoints": "You don't have enough points to perform that action"
    "moderator_marker": "Mod"
    "trusted_marker": "T"
    "trusted_marker_tooltip": "Click to see how to earn the Trusted Badge for yourself"
    "moderator_user": "This user is a moderator"
    "moderator": "Moderator"
    "no_password": "You haven't set a password yet and you could lose your account. <a href=\"#{"#profile"}\">Go to your profile</a> then click \"Change password\" to set up a password for your account."
    "change_pass": "<a href=\"{url}/profile\" target=\"_blank\">Change password</a>."
    "change_notifications": "<a href=\"{url}/profile\" target=\"_blank\">Change notification options</a>."
    "change_settings": "<a href=\"{url}/profile\" target=\"_blank\"><i class=\"icon-cogs\"></i> Settings</a>"
    "subscription_options": "Subscription options"
    "options": "Options"
    "subscribe": "Subscribe"
    "subscribe_articles": "Subscribe to new articles"
    "subscribe_own": "Subscribe to my own content"
    "subscribe_auto": "Auto subscribe to the conversations I take part in"
    "subscribe_conversations": "Subscribe to updates"
    "subscribe_updates": "Subscribe to updates in this conversation"
    "subscribe_success": "You have successfully subscribed"
    "unsubscribe_success": "You have successfully unsubscribed"
    "read_more": "(read more)"
    "read_less": "(read less)"
    "more_new_inv_comments": "You have {count} unseen new comment{plural}!<br><small>(click to load {inv_count} more)</small>"
    "more_new_comments": "You have {count} unseen new comment{plural}!"
    "more_inv_comments": "Click to load {inv_count} new comment{plural}!"
    "more_bubble_notif": "<small>You have {count} unseen notification{plural}!<br>(click to see)</small>"
    "show_more": "Show more"
    "show_20_more": "Show 20 more comments"
    "show_25_more": "Show 25 more comments"
    "show_50_more": "Show 50 more comments"
    "show_all_more": "Show all"
    "delete_all": "Delete all"
    "format_text": "Formatting text"
    "select_tags_placeholder": "Select your category"
    "no_context_filter": "Categories"
    "head_categories": "Category"
    "challenge_ad_text": "Don't agree with a comment?"
    "challenge_ad_text_2": "Challenge it to receive points."
    "learn_more": "Learn More"
    "best_answer": "Best Answer"
    "best_answer_with_points": "Best Answer, {value} point(s) awarded"
    "challenged_comment": "Comment challenged"
    "challenge_cost_note": "This challenge costs {value} points"
    "challenge_free_note": "Your first challenge is free!"
    "challenged_question": "Question challenged"
    "go_to_forums": "Go to forums"
    "go_to_competitions": "Go to competitions"
    "go_to_article": "Go to article"
    "prev_activity": "Previous Activity"
    "goto_comment": "Go to this comment"
    "go_to_comments": "Go to comments"
    "is_question": "I am asking a question to the community."
    "points_offered_note": 'Offer <input type="text" class="question_points_offered" maxlength="3"/> of my points to the best answer'
    "question_view_points_offered": "{value} point(s) up for grabs"
    "comment_active_replies": "{value} users  are replying..."
    "comment_deleted": "This comment has been deleted"
    "context_deleted": "This forum topic has been deleted"
    "question_deleted": "This question has been deleted"
    "answer_deleted": "This answer has been deleted"
    "challenge_deleted": "This challenge has been deleted"
    "bet_deleted": "This Yolo has been deleted"
    "said": "said"
    "show_embedded_items": "Show embedded content"
    "hide_embedded_items": "Hide embedded content"
    "challenged": "challenged"
    "challenge_winner": "Challenge winner"
    "competitions": "Competitions"
    "competition_banner": "Competition: <strong>{title}</strong> from {start} to {end}; read the <a target='_blank' href='{rules}'>Rules</a> and join the conversation!</a>"
    "competition_header": "<i class='icon-trophy'></i> Win <a href='{prize_url}'>{prize}</a> by joining the {community} community and commenting between {start} - {end} (<span class='countdown'>{countdown}</span> remaining, see <a target='_blank' href='{rules}'>rules</a>)."
    "competition_header_share": "To join the competition share a comment or article."
    "competition_starts_on": "Competition starts on"
    "competition_active": "Competition is active"
    "competition_ended_on": "Competition ended on"
    "competition_active_until": "Competition active until"
    "competition_winner": "Winner"
    "competition_rules": "Rules"
    "competition_prize": "Prize"
    "competition_ranking_title": "Competition Ranking"
    "competition_win": "Win {prize} by having rank #1 <strong>{badge_icon}</strong> on {end}."
    "competition_win_prize": "Win <a href='prize_url'>{prize}</a> by having rank #1 <strong>{badge_icon}</strong> on {end}."
    "ranking_hot": "Hot"
    "thread_title": "Thread title"
    "title": "Title"
    "rank": "Rank"
    "help_and_support": "Help & Support"
    "footer_add_burnzone_short": 'Add to my Site'
    "footer_add_burnzone": 'Add <span class="footer_burnzone">BurnZone</span>'
    "title_like_up": "Like this comment"
    "title_like_down": "Dislike this comment"
    "title_best_answer": "This is the best answer, based on votes received"
    "title_challenged": "This comment got challenged"
    "title_reply": "Reply to this comment"
    "title_reply_with_bet": "Reply to this comment with a Yolo"
    "title_challenge": "Challenge this comment to share an opposing view"
    "title_share": "Share this on social media"
    "title_flag": "Flag for spam"
    "title_vote_up": "Vote up"
    "title_vote_down": "Retract vote"
    "title_challenged_side": "This is the comment that got challenged. Vote if you agree with the commenter."
    "title_challenger_side": "This is the challenger's opinion. Vote if you agree with his opposing point of view."
    "title_reply_comment": "Comment this opinion"
    "title_reply_question": "Comment this question"
    "title_reply_answer": "Comment this answer"
    "title_reply_challenge": "Comment this challenge"
    "title_question_answer": "Answer this question"
    "title_answer_note": "This is an answer to the above question"
    "title_is_question": "Check this if you're posting a question"
    "title_points_offered": "Type how many points will the author of the best answer get"
    "title_logo": "BurnZone Commenting"
    "title_goto_comment": "Go to this comment"
    "title_input_forum_title_counter": "Remaining characters"
    "title_view_original": "View the original comment"
    "title_self_promote": "Pay points to have your comment sent to the top of the conversation"
    "title_promoted_points_note": "This comment is promoted"
    "title_promoted_points_note_user": "User {user} promoted this comment"
    "new_notifications": "{value}"
    "fund_comment": "Ignite"
    "fund_comment_info": "Ignite this comment to show appreciation for this post."
    "fund_comment_burning": "Burning"
    "fund_comment_success": "You have successfully ignited this comment."
    "fund_challenge_challenger_success": "You have successfully ignited the challenger's opinion."
    "fund_challenge_challenged_success": "You have successfully ignited the original challenged comment."
    "funded_comments": "Burning"
    "funded_for_site": "All conversations"
    "funded_for_conv": "In this conversation"
    "no_funders": "x{value}"
    "error_api_notexists": "This item does not exist"
    "empty_collection_generic": "None"
    "empty_yolos_thread": "No one has submitted a Yolo yet"
    "user_notif_NEW_CONVERSATION": "A new article was published on {sitename}"
    "user_notif_WIN_QUESTION": "You had the best answer!"
    "user_notif_WIN_QUESTION_here": "You had the best answer!"
    "user_notif_NEW_COMMENT": "New comment"
    "user_notif_NEW_COMMENT_here": "New comment"
    "user_notif_NEW_BET": "New Yolo"
    "user_notif_NEW_BET_here": "New Yolo"
    "user_notif_BET_TARGETED": "{username} targeted you in a Yolo"
    "user_notif_BET_TARGETED_here": "{username} targeted you in a Yolo"
    "user_notif_BET_ACCEPTED": "{username} accepted a Yolo"
    "user_notif_BET_ACCEPTED_here": "{username} accepted a Yolo"
    "user_notif_BET_DECLINED": "{username} declined a Yolo"
    "user_notif_BET_DECLINED_here": "{username} declined a Yolo"
    "user_notif_BET_FORFEITED": "{username} acknowledged loss in a Yolo"
    "user_notif_BET_FORFEITED_here": "{username} acknowledged loss in a Yolo"
    "user_notif_BET_CLAIMED": "{username} has claimed a Yolo"
    "user_notif_BET_CLAIMED_here": "{username} has claimed a Yolo"
    "user_notif_BET_UNRESOLVED": "An unresolved Yolo requires your attention"
    "user_notif_BET_UNRESOLVED_here": "An unresolved Yolo requires your attention"
    "user_notif_BET_SENT_TO_MOD": "Yolo sent to moderation"
    "user_notif_BET_SENT_TO_MOD_here": "Yolo sent to moderation"
    "user_notif_BET_RESOLVED_PTS": "Yolo resolved"
    "user_notif_BET_RESOLVED_PTS_here": "Yolo resolved"
    "user_notif_BET_WIN": "You have won {points} points in a Yolo"
    "user_notif_BET_WIN_here": "You have won {points} points in a Yolo"
    "user_notif_BET_LOSE": "You have lost {points} points in a Yolo"
    "user_notif_BET_LOSE_here": "You have lost {points} points in a Yolo"
    "user_notif_BET_TIE": "Your Yolo has ended in a tie"
    "user_notif_BET_TIE_here": "Your Yolo has ended in a tie"
    "user_notif_BET_CLOSED": "Yolo closed"
    "user_notif_BET_CLOSED_here": "Yolo closed"
    "user_notif_BET_FORF_STARTED": "Resolve your Yolo"
    "user_notif_BET_FORF_STARTED_here": "Resolve your Yolo"
    "user_notif_BET_FORF_CLOSED": "Yolo resolution window closed"
    "user_notif_BET_FORF_CLOSED_here": "Yolo resolution window closed"
    "user_notif_BET_REMIND_FORF": "Reminder to resolve your Yolo"
    "user_notif_BET_REMIND_FORF_here": "Reminder to resolve your Yolo"
    "user_notif_MENTION": "{username} mentioned you in a comment"
    "user_notif_ANSWER": "{username} answered your comment"
    "user_notif_ANSWER_here": "{username} answered your comment"
    "user_notif_PROMOTED_COMMENT": "Your comment has been promoted"
    "user_notif_PROMOTED_COMMENT_here": "Your comment has been promoted"
    "user_notif_OUTBID_COMMENT": "Your comment has been demoted because another user has promoted their comment with more points.  Add more points to promote your comment again."
    "user_notif_OUTBID_COMMENT_here": "Your comment has been demoted because another user has promoted their comment with more points.  Add more points to promote your comment again."
    "user_notif_REPLY": "{username} replied to your comment"
    "user_notif_REPLY_here": "{username} replied to your comment"
    "user_notif_CHALLENGED": "{username} challenged your comment"
    "user_notif_CHALLENGED_here": "{username} challenged your comment"
    "user_notif_NEW_CHALLENGE": "New challenge"
    "user_notif_NEW_CHALLENGE_here": "New challenge"
    "user_notif_WIN_CHALLENGE": "You won your challenge!"
    "user_notif_WIN_CHALLENGE_here": "You won your challenge!"
    "user_notif_LOSE_CHALLENGE": "You lost your challenge!"
    "user_notif_LOSE_CHALLENGE_here": "You lost your challenge!"
    "user_notif_VOTE": "{username} voted you in a challenge"
    "user_notif_VOTE_here": "{username} voted you in a challenge"
    "user_notif_VOTE_down": "Someone retracted the vote for you in a challenge"
    "user_notif_VOTE_down_here": "Someone retracted the vote for you in a challenge"
    "user_notif_LIKE_ANSWER": "{username} liked your answer"
    "user_notif_LIKE_ANSWER_here": "{username} liked your answer"
    "user_notif_LIKE_ANSWER_down": "Someone retracted the vote for your answer"
    "user_notif_LIKE_ANSWER_down_here": "Someone retracted the vote for your answer"
    "user_notif_LIKE_COMMENT": "{username} liked your comment"
    "user_notif_LIKE_COMMENT_here": "{username} liked your comment"
    "user_notif_LIKE_COMMENT_down": "Someone retracted the like for your comment"
    "user_notif_LIKE_COMMENT_down_here": "Someone retracted the like for your comment"
    "user_notif_LIKE_ANSWER_UPDOWN": "{username} liked your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_here": "{username} liked your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_retract": "Someone retracted the like for your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_retract_here": "Someone retracted the like for your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_down": "Someone down-liked your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_down_here": "Someone down-liked your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_down_retract": "Someone retracted the down-like for your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_down_retract_here": "Someone retracted the down-like for your answer"
    "user_notif_LIKE_COMMENT_UPDOWN": "{username} liked your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_here": "{username} liked your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_retract": "Someone retracted the like for your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_retract_here": "Someone retracted the like for your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_down": "Someone down-liked your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_down_here": "Someone down-liked your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_down_retract": "Someone retracted the down-like for your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_down_retract_here": "Someone retracted the down-like for your comment"
    "user_notif_COMPETITION_START": "Competition started: {title}"
    "user_notif_COMPETITION_STARTING": "{days} days until competition starts: {title}"
    "user_notif_COMPETITION_END": "Competition ended: {title}"
    "user_notif_COMPETITION_ENDING": "Competition {title} ending in {days} days"
    "user_notif_IGNITE_COMMENT": "{username} ignited your comment"
    "bet_filter_by": "Filter by: {filter}"
    "date_filter_all": "All"
    "date_filter_start_end": "From {start} to {end}"
    "date_filter_only_end": "Until {end}"
    "date_filter_only_start": "Since {start}"
    "date_filter_today": "Today"
    "date_filter_yesterday": "Yesterday"
    "date_filter_last_7_days": "Last 7 days"
    "date_filter_last_30_days": "Last 30 days"
    "date_filter_this_month": "This month"
    "date_filter_last_month": "Last month"
    "date_filter_custom": "Custom"
    "date_filter_apply": "Apply"
    "date_filter_cancel": "Cancel"
    "date_filter_to": "to"
    "date_filter_from": "from"
    "date_filter_separator": " to "
    "filter_activity_rating": "Most Active"
    "help_burning_comment_user": "{user} was ignited as a reward for posting outstanding content. Both users get 30 days of premium features. <a class='learn_more_popover' target='_blank' href='http://help.theburn-zone.com/customer/portal/articles/1944062'>Learn more here</a>"
    "help_burning_comment": "This burning comment was ignited by a user to show appreciation for this post. Both users are awarded extra features for 30 days. <a class='learn_more_popover' target='_blank' href='http://help.theburn-zone.com/customer/portal/articles/1944062'>Learn more here</a>"
    "help_ignite": "Ignite a comment to reward a user for outstanding content. Both users get 30 days of premium features. <a class='learn_more_popover' target='_blank' href='http://help.theburn-zone.com/customer/portal/articles/1944062'>Learn more here</a>"
    "help_burning": "Burning comments have been rewarded for outstanding content. Click to view or <a class='learn_more_popover' target='_blank' href='http://help.theburn-zone.com/customer/portal/articles/1944062'>learn more here</a>."
    "help_demo_payment": "You are running a BurnZone DEMO. Transactions will not be processed. A new page with credit card information that can be used for testing will open. Please use one of those if you want to test the ignite feature."
    "top_forum_threads": "Top Forum Threads:"
    "top_articles": "Top Articles:"
}
