module.exports = {
  name: "Português"
  code: "pt"
  terms:
    "browser_support": "O Burnzone não é compatível com teu navegador. Por favor, atualiza o navegador para a versão mais recente ou altera o teu navegador para o Mozilla ou o Chrome."
    "login_to_comment": " Entra para comentar"
    "login_to_challenge": " Entra para desafiar"
    "login_with": " Entrar com"
    "signup_with": " Regista-te com"
    "sign_in": " Entra"
    "sign_in_using": " Entra com"
    "settings": "Configurações"
    "or": " ou"
    "comment": " Comentário"
    "comments": " Comentários"
    "challenges": " Desafios"
    "questions": " Perguntas"
    "likes": " gostos"
    "write_comment": " Partilha os teus pensamentos ..."
    "write_answer": " Insere aqui a tua resposta"
    "answered": " respondidas"
    "submit": " Submeter"
    "cancel": " Cancelar"
    "sort_by": " organizadas por"
    "get_burnzone": " Obter comentários BurnZone"
    "oldest": "Mais antigas"
    "newest": "Mais recentes"
    "points": " Pontos"
    "points_short": " pts"
    "answers": " Respostas"
    "votes": " Votos"
    "no_points": " {value} Pontos"
    "reply": " Responder"
    "reply_in_challenge": " Responder no desafio"
    "comment_in_challenge": " Comentário no desafio"
    "challenge": " Desafio"
    "question": "Pergunta"
    "key_point": " Ponto-chave"
    "no_all_activities": " {value} Comentário (s)"
    "no_comments": " {value} comentário (s)"
    "no_challenges": " {value} desafio (s)"
    "no_questions": " {value} pergunta (s)"
    "no_answers": " {value} resposta (s)"
    "enter_your_pv": " Insire o teu ponto de vista ..."
    "vs": " vs"
    "enter_fb_uid": "Insere o teu ID de utilizador do Facebook aqui"
    "non_verified_user": "O endereço de e-mail deste utilizador não foi verificada"
    "logout": " Sair"
    "gravatar_profile": " Perfil no Gravatar"
    "days_ago": " {value} dia(s) atrás"
    "hours_ago": " {value} hora(s) atrás"
    "minutes_ago": " {value} minuto(s) atrás"
    "ends_in_days": " Termina em {value} dia(s)"
    "ends_in_hours": " Termina em {value} horas (s)"
    "ends_in_minutes": " Termina em {value} minuto(s)"
    "challenge_ended": " Terminou"
    "ends_now": "está prestes a terminar"
    "just_now": " agora mesmo"
    "exact_time": " em {value}"
    "my_profile": "O meu perfil"
    "challenge_comment": " Ponto de vista do Desafiador:"
    "original_comment": " Resumo do ponto desafiado:"
    "or_login_with": " ou entrar com"
    "flag": " Bandeira"
    "answer": " Resposta"
    "share": "Partilhar"
    "share_challenge": " Partilhar este desafio:"
    "share_conversation": " Partilhar esta conversa"
    "share_tw": " Partilhar no twitter"
    "share_fb": " Partilhar no Facebook"
    "error_loading": "Não foi possível carregar esta conversa."
    "error_embed_sitenotexists": " Nome do site inválido."
    "error_embed_nourl": " URL de conversa inválido."
    "error_embed_embedlocalhost": " Não é possível inserir uma conversa no site BurnZone."
    "error_embed_forceid": " A tua conta BurnZone está configurado para forçar IDs de conversação, mas não forneceste nehum."
    "error_embed_useqs": "A tua conta BurnZone está configurada para usar chaves de sequência de consulta, mas não as forneste todas."
    "error_embed_url_not_reachable": "O teu artigo deve estar públicamente acessível através da internet."
    "flagged": "Marcado"
    "flagged_challenge": " Este desafio foi marcado"
    "change_image": " Escolhe a tua imagem"
    "change_your_data": " Altera os teus dados de perfil"
    "change_name": " Nome"
    "change_email": " Email"
    "change_submit": " Mudar"
    "use_grav_image": " Gravatar"
    "use_fb_image": " Facebook"
    "error_access_api": " Houve um problema ao processar o teu pedido"
    "user_banned": " Fostei banido por agora"
    "create_comment_success": " O teu comentário foi criado com sucesso"
    "create_question_success": "A tua pergunta foi criada com sucesso"
    "create_answer_success": " A tua resposta foi criada com sucesso"
    "create_comment_notallowed": " Estás temporáriamente proíbido de comentar"
    "create_comment_approval": " O teu comentário aguarda aprovação do moderador"
    "create_question_approval": "A tua pergunta aguarda aprovação do moderador"
    "create_answer_approval": "A tua resposta aguarda aprovação do moderador"
    "create_challenge_success": "O teu desafio foi criado com sucesso"
    "create_challenge_notallowed": "Estás temporáriamente proíbido de desafiar comentários"
    "create_challenge_approval": "O teu desafio aguarda aprovação do moderador"
    "create_challenge_notpoints": " Não tens pontos suficientes para desafiar este comentário"
    "create_challenge_denied": " Não podes desafiar o teu próprio comentário, um comentário que não existe, um comentário apagado ou um comentário que já foi desafiado (o desafio poderá não ser aprovado)"
    "vote_commentinch_user_in_challenge": " Não podes votar, porque estás no desafio"
    "vote_commentinch_once": " Só podes votar uma vez e só podes retirar o teu voto anterior"
    "vote_ch_ended": " Não podes votar num desafio que terminou"
    "like_comment_once": " Só podes gostar uma vez e só podes retirar o teu gosto anterior"
    "like_comment_retry": " Houve um conflito com o teu pedido. Por favor, tenta novamente."
    "like_own_comment": " Não podes gostar do teu próprio comentário"
    "like_author_unknown": " Alguém"
    "needs_login": " Tens que entrar primeiro"
    "needs_moderator": " Precisas de  permissões de moderador para isto"
    "user_exists": " Este endereço de e-mail já está em uso. Por favor, tenta um novo."
    "edit_profile": " Pode alterar o Teu nome e avatar a partir da tua página de perfil"
    "delete": "Apagar"
    "top_answer": " Resposta Top"
    "create_user": " Ou criar um nome de utilizador BurnZone"
    "create_user_expl": " Criar um nome de utilizador permite-te comentar, votar e ser parte do quadro de classificações."
    "anon_name": " Nome"
    "anon_email": " Email"
    "anon_pass": " Senha"
    "invalid_name": " Por favor insere um nome"
    "invalid_email": " Por favor insere um e-mail válido"
    "invalid_password": " Por favor insere uma senha válida"
    "email_must_be_valid": " Deve ser válido para verificar"
    "site_leaderboard": "Quadro de classificações do site"
    "conversation_leaderboard": "Quadro de classificações de conversa"
    "site_leaderboard_title": " Estes rankings são baseados em todas as atividades que os utilizadores têm em todo o site"
    "conversation_leaderboard_title": " Estes rankings são baseados na atividade neste único artigo"
    "how_to_points": " Como faço para ganhar pontos?"
    "not_verified": " O teu endereço de email não é verificado. Não tens permissão para sinalizar conteúdo impróprio e só podes votar um número limitado de vezes."
    "no_password": " Ainda não definiste uma senha e podes perder a tua conta. <a href=\"#{"#profile"}\"> Vái para o teu perfil </a>, em seguida, cliqua em \" Alterar senha \"para configurar uma senha para tua conta."
    "change_pass": " <a href=\"{url}/profile\" target=\"_blank\"> Alterar senha </a>."
    "change_notifications": " <a href=\"{url}/profile\" target=\"_blank\"> Alterar opções de notificação </a>."
    "subscription_options": " Opções de subscrição"
    "subscribe": " Subscrever"
    "subscribe_own": " Subscrever o meu próprio conteúdo"
    "subscribe_auto": " Subscrever automáticamente as conversas em que eu participo"
    "subscribe_conversations": " Subscrever novos artigos"
    "subscribe_updates": " Subscrever atualizações nesta conversa"
    "subscribe_success": " Subscreveste com sucesso"
    "unsubscribe_success": " Anulaste a tua subscrição com sucesso"
    "read_more": " (Ler mais)"
    "read_less": " (Ler mais)"
    "show_more": " Mostrar mais"
    "delete_all": " Apagar tudo"
    "format_text": " Formatação de texto"
    "challenge_ad_text": " Não concordas com um comentário?"
    "challenge_ad_text_2": " Desafia para receber pontos."
    "learn_more": " Saiber mais"
    "best_answer": " Melhor Resposta"
    "challenged_comment": " Comentário desafiado"
    "challenged_question": " Pergunta desafiada"
    "go_to_comments": " Voltar para comentários"
    "is_question": " Isto é uma pergunta"
    "comment_deleted": " Este comentário foi apagado"
    "question_deleted": " Esta pergunta foi apagada"
    "answer_deleted": " Esta resposta foi apagada"
    "challenge_deleted": " Este desafio foi apagado"
    "said": " dito"
    "challenged": " desafiado"
    "challenge_winner": " Desafiar vencedor"
    "title_like_up": " Gostar deste comentário"
    "title_like_down": " Não gostar deste comentário"
    "title_best_answer": " Esta é a melhor resposta, com base nos votos recebidos"
    "title_challenged": " Este comentário foi desafiado"
    "title_reply": " Responder a este comentário"
    "title_challenge": " Desafia este comentário para partilhar uma opinião oposta"
    "title_share": " Partilhar nas redes sociais"
    "title_flag": "Marcar como spam"
    "title_vote_up": " Votar"
    "title_vote_down": " Retirar voto"
    "title_challenged_side": " Este é o comentário que foi desafiado. Vota se concordas com o comentador."
    "title_challenger_side": " Esta é a opinião do desafiador. Vota se concordas com a sua opinião oposta."
    "title_reply_comment": " Comenta esta opinião"
    "title_reply_question": " Comenta esta pergunta"
    "title_reply_answer": " Comenta esta resposta"
    "title_reply_challenge": " Comentar este desafio"
    "title_question_answer": " Responde a esta pergunta"
    "title_answer_note": " Esta é uma resposta relativa à pergunta acima"
    "title_is_question": " Marca esta opção se estás a fazer uma pergunta"
    "title_logo": " Comentários BurnZone"
    "new_notifications": " {value}"
    "user_notif_NEW_CONVERSATION": " Um novo artigo foi publicado em {sitename}"
    "user_notif_WIN_QUESTION": " Tiveste a melhor resposta!"
    "user_notif_WIN_QUESTION_here": " Tiveste a melhor resposta!"
    "user_notif_NEW_COMMENT": " Novo comentário"
    "user_notif_NEW_COMMENT_here": " Novo comentário"
    "user_notif_ANSWER": " {username} respondeu ao teu comentário"
    "user_notif_ANSWER_here": " {username} respondeu ao teu comentário"
    "user_notif_REPLY": " {username} respondeu ao teu comentário"
    "user_notif_REPLY_here": " {username} respondeu ao teu comentário"
    "user_notif_CHALLENGED": " {username} desafiou o teu comentário"
    "user_notif_CHALLENGED_here": " {username} desafiou o teu comentário"
    "user_notif_NEW_CHALLENGE": " Novo desafio"
    "user_notif_NEW_CHALLENGE_here": " Novo desafio"
    "user_notif_WIN_CHALLENGE": " Ganhas-te o teu desafio!"
    "user_notif_WIN_CHALLENGE_here": " Ganhas-te o teu desafio!"
    "user_notif_LOSE_CHALLENGE": " Perdes-te o teu desafio!"
    "user_notif_LOSE_CHALLENGE_here": " Perdes-te o teu desafio!"
    "user_notif_VOTE": " {username} votou em ti num desafio"
    "user_notif_VOTE_here": " {username} votou em ti num desafio"
    "user_notif_VOTE_down": " Alguém retirou o voto em ti num desafio"
    "user_notif_VOTE_down_here": " Alguém retirou o voto em ti num desafio"
    "user_notif_LIKE_ANSWER": " {username} gostou da tua resposta"
    "competitions": "Competições"
    "competition_banner": "Competição: <strong> {title} </strong> a partir de {start} para {end}; leia a <a target='_blank' href='{rules}'> Regras </a> e faça parte da conversa </a> "
    "competition_header": "<i class='icon-trophy'> </i> Ganhar <a href='{prize_url}'> {prize} </a>, unindo a {community} comunidade e comentando entre {start} - {end} (<span class='countdown'> {countdown} </span> restante, consulte <a target='_blank' href='{rules}'> regras </a>)"
    "competition_starts_on": "A competição começa em"
    "competition_active": "A competição está ativo"
    "competition_ended_on": "A competição terminou em"
    "competition_active_until": "A concorrência ativa até"
    "competition_winner": "Vencedor"
    "competition_rules": "Regras"
    "competition_prize": "Prémio"
    "competition_ranking_title": "Competição Ranking"
    "user_notif_COMPETITION_START": "A competição começou: {title}"
    "user_notif_COMPETITION_STARTING": "{days} dias até o início da competição: {title}"
    "user_notif_COMPETITION_END": "A competição terminou: {title}"
    "user_notif_COMPETITION_ENDING": "A competição {title} terminando em {days} dias"
    "submit_comment": "Enviar comentário"
    "submit_question": "Enviar pergunta"
    "reg_and_submit_comment": "Register"
}

