module.exports = {
  name: "Deutsch"
  code: "de"
  terms:
    "browser_support": "Burnzone wird von Ihrem Browser nicht unterstützt. Bitte aktualisieren Sie Ihren Browser auf die neueste Version oder wechseln Sie zu Mozilla oder Chrome."
    "login_to_comment": "Zum Kommentieren loggen Sie sich bitte ein"
    "login_to_challenge": "Zum Herausfordern loggen Sie sich bitte ein"
    "login_with": " Einloggen mit"
    "signup_with": " Anmelden mit"
    "sign_in": " Anmelden"
    "sign_in_using": " Melden Sie sich an mit"
    "settings": "Einstellungen"
    "or": " oder"
    "comment": " Kommentar"
    "comments": " Kommentare"
    "challenges": " Herausforderungen"
    "questions": " Fragen"
    "likes": "Gefällt mir"
    "write_comment": " Teilen Sie Ihre Gedanken ..."
    "write_answer": " Geben Sie Ihre Antwort hier ein"
    "answered": " beantwortet"
    "submit": "Senden"
    "cancel": "Löschen"
    "sort_by": " sortiert nach"
    "get_burnzone": " Erhalten Sie BurnZone Kommentare"
    "oldest": " Älteste"
    "newest": " Neueste"
    "points": " Punkte"
    "points_short": " pts"
    "answers": " Antworten"
    "votes": " Stimmen"
    "no_points": " {value} Punkte"
    "reply": "antworten"
    "reply_in_challenge": " antworten in der Herausforderung"
    "comment_in_challenge": " Kommentar in der Herausforderung"
    "challenge": " Herausforderung"
    "question": "Frage"
    "key_point": "Schwerpunkt"
    "no_all_activities": " {value} Kommentar(e)"
    "no_comments": " {value} Kommentar(e)"
    "no_challenges": " {value} Herausforderung(en)"
    "no_questions": " {value} Frage(n)"
    "no_answers": " {value} Antwort(en)"
    "enter_your_pv": " Geben Sie Ihre Ansicht ein ..."
    "vs": " vs"
    "enter_fb_uid": "Geben Sie die Facebook user-ID hier ein"
    "non_verified_user": "Die E-Mail-Adresse des Users wurde nicht bestätigt"
    "logout": " Abmelden"
    "gravatar_profile": " Profil auf Gravatar"
    "days_ago": " {value} vor Tag(en)"
    "hours_ago": " {value} vor Stunde(n)"
    "minutes_ago": " {value} vor Minute(n)"
    "ends_in_days": " Endet in {value} Tag(en)"
    "ends_in_hours": " Endet in {value} Stunden(en)"
    "ends_in_minutes": " Endet in {value} Minute(n)"
    "challenge_ended": "Beendet"
    "ends_now": " Sollte nun jeden Moment enden"
    "just_now": " soeben"
    "exact_time": " auf {value}"
    "my_profile": " Mein Profil"
    "challenge_comment": "Ansicht des Herausforderers:"
    "original_comment": "Zusammenfassung der herausgeforderten Punkte:"
    "or_login_with": " oder melden Sie sich an mit"
    "flag": " Flagge"
    "answer": " Antwort"
    "share": " Aktie"
    "share_challenge": " Teilen Sie diese Herausforderung:"
    "share_conversation": " Teile Sie dieses Gespräch"
    "share_tw": " Teilen Sie auf Twitter"
    "share_fb": "Teilen Sie auf Facebook"
    "error_loading": "Das Gespräch konnte nicht hochgeladen werden."
    "error_embed_sitenotexists": " Ungültiger Seitenname."
    "error_embed_nourl": " Ungültige Gesprächs-URL."
    "error_embed_embedlocalhost": " Das Gespräch kann auf der BurnZone Website eingebaut werden."
    "error_embed_forceid": " Die Konfigurierung Ihres BurnZone Kontos erfordert eine Gespächs-ID, Sie haben aber keine angegeben."
    "error_embed_useqs": " Die Konfigurierung Ihres BurnZone Kontos erfordert Query-String-Tasten, aber Sie haben keine angegeben."
    "error_embed_url_not_reachable": " Ihr Artikel muss im Internet öffentlich zugänglich sein."
    "flagged": " Gekennzeichnet"
    "flagged_challenge": " Diese Herausforderung wurde markiert"
    "change_image": " Erstellen Sie Ihr Bild"
    "change_your_data": " Ändern Sie Ihre Profildaten"
    "change_name": " Name"
    "change_email": " E-Mail"
    "change_submit": " Ändern"
    "use_grav_image": " Gravatar"
    "use_fb_image": " Facebook"
    "error_access_api": " Es gab ein Problem bei der Bearbeitung Ihrer Anfrage"
    "user_banned": " Sie wurden für den Moment blockiert"
    "create_comment_success": "Ihr Kommentar wurde erfolgreich erstellt"
    "create_question_success": " Ihre Frage wurde erfolgreich erstellt"
    "create_answer_success": " Ihre Antwort wurde erfolgreich erstellt"
    "create_comment_notallowed": " Für den Moment wurden blockiert, Sie können keine Kommentare abgeben"
    "create_comment_approval": " Ihr Kommentar benötigt die Zustimmung eines Moderators"
    "create_question_approval": " Ihre Frage benötigt die Zustimmung eines Moderators"
    "create_answer_approval": " Ihre Antwort benötigt die Zustimmung eines Moderators"
    "create_challenge_success": " Ihre Herausforderungen wurden erfolgreich erstellt "
    "create_challenge_notallowed": " Für den Moment wurden Sie für das Kommentieren der Herausforderungen blockiert"
    "create_challenge_approval": " Ihre Herausforderung benötigt die Zustimmung eines Moderators"
    "create_challenge_notpoints": " Sie haben nicht genügend Punkte, um diesen Kommentar heruaszufordern"
    "create_challenge_denied": " Sie können Ihren eigenen Kommentar, einen nicht bestehenden  Kommentar, einen gelöschten oder einen bereits herausgeforderten Kommentar (die Herausforderung könnte noch nicht bestätigt sein) nicht herausfordern"
    "vote_commentinch_user_in_challenge": " Sie können nicht wählen, da Sie sich in der Herausforderung befinden"
    "vote_commentinch_once": " Sie können nur einmal wählen und Sie können nur Ihre vorherige Abstimmung zurückziehen"
    "vote_ch_ended": " Sie können nicht in einer abgeschlossenen Herausforderung wählen"
    "like_comment_once": " Sie können Gefällt mir nur einmal verwenden und nur Ihr vorheriges Gefällt mir rückgängig machen"
    "like_comment_retry": " Es gab ein Problem bei Ihrer Anfrage. Bitte versuchen Sie es erneut."
    "like_own_comment": "Gefällt mir gilt nicht bei eigenen Kommentaren"
    "like_author_unknown": " Jemand"
    "needs_login": " Sie müssen sich zuerst einloggen"
    "needs_moderator": "Die Berechtigung des Modertors ist dafür nötig"
    "user_exists": " Diese E-Mail-Adresse wird bereits von einem anderen User verwendet. Bitte versuchen Sie es mit einer anderen."
    "edit_profile": " Sie können Ihren Namen und Avatar auf Ihrer Profilseite ändern"
    "delete": " Löschen"
    "top_answer": " Top Antwort"
    "create_user": " Oder erstellen Sie einen BurnZone-User"
    "create_user_expl": " Als Benutzer können Sie kommentieren, wählen und werden Teil der Rangliste."
    "anon_name": " Name"
    "anon_email": " E-Mail"
    "anon_pass": " Passwort"
    "invalid_name": " Bitte geben Sie einen Namen ein"
    "invalid_email": " Bitte geben Sie eine gültige E-Mail-Adresse ein"
    "invalid_password": " Bitte geben Sie ein gültiges Passwort ein"
    "email_must_be_valid": " Muss gültig sein, um zu bestätigen"
    "site_leaderboard": " Site-Rangliste"
    "conversation_leaderboard": " Konversationsrangliste"
    "site_leaderboard_title": " Diese Ranglisten werden aufgrund aller Tätigkeiten der Nutzer auf der gesamten Website erstellt"
    "conversation_leaderboard_title": " Diese Ranglisten werden aufgrund der Aktivität eines einzigen Artikels erstellt"
    "how_to_points": " Wie bekomme ich Punkte?"
    "not_verified": " Ihre E-Mail-Adresse ist nicht verifiziert. Sie sind nicht ermächtigt unpassenden Inhalt zu kennzeichnen und die Anzahl der Abstimmungen ist begrenzt."
    "no_password": " Sie haben noch kein Passwort bestimmt ist und könnten Ihr Konto verlieren. <a href=\"#{"#profile"}\"> Gehen Sie zu Ihrem Profil </a> klicken Sie dann auf \"Passwort ändern \" um für Ihr Konto ein Passwort einzurichten."
    "change_pass": " <a href=\"{url}/profile\" target=\"_blank\"> Passwort ändern </a>."
    "change_notifications": " <a href=\"{url}/profile\" target=\"_blank\"> Ändern Sie die Benachrichtigungsoptionen </a>."
    "subscription_options": " Abo-Optionen"
    "subscribe": "Erstellen"
    "subscribe_own": "Erstellen meiner eigenen Inhalte"
    "subscribe_auto": "Automatisches Abonnieren der Gespräche, an denen ich teilnehme"
    "subscribe_conversations": "Abonnieren Sie neuer Artikel"
    "subscribe_updates": "Abonnieren Sie Updates in diesem Gespräch"
    "subscribe_success": " Sie haben Sich erfolgreich abgemeldet"
    "unsubscribe_success": " Sie haben Sich erfolgreich abgemeldet"
    "read_more": " (Mehr lesen)"
    "read_less": " (Weniger lesen)"
    "show_more": " Mehr anzeigen"
    "delete_all": " Alle löschen"
    "format_text": "Text formatieren"
    "challenge_ad_text": " Mit einem Kommentar nicht einverstanden?"
    "challenge_ad_text_2": " Fordern Sie es heraus, um Punkte zu erhalten."
    "learn_more": " Erfahren Sie mehr"
    "best_answer": " Beste Antwort"
    "challenged_comment": " Herausgeforderter Kommentar "
    "challenged_question": "Herausgeforderte Frage"
    "go_to_comments": " Zurück zu den Kommentaren"
    "is_question": " Dies ist eine Frage"
    "comment_deleted": " Dieser Kommentar wurde gelöscht"
    "question_deleted": " Diese Frage wurde gelöscht"
    "answer_deleted": " Diese Antwort wurde gelöscht"
    "challenge_deleted": " Diese Herausforderung wurde gelöscht"
    "said": " sagte"
    "challenged": " herausgefordert"
    "challenge_winner": " Challenge-Gewinner"
    "title_like_up": " Gefällt Ihnen dieser Kommentar"
    "title_like_down": " Gefällt Ihnen dieser Kommentar nicht"
    "title_best_answer": " Das ist die beste Antwort, basierend auf den erhaltenen Stimmen"
    "title_challenged": " Dieser Kommentar wurde herausgefordert"
    "title_reply": " Auf diesen Kommentar antworten"
    "title_challenge": " Fordern Sie diesen Kommentar heraus, um eine entgegengesetzte Ansicht zu teilen"
    "title_share": " Teilen Sie diese auf Social Media"
    "title_flag": "Als Spam kennzeichnen"
    "title_vote_up": "Stimmen Sie ab"
    "title_vote_down": " Abstimmung zurückziehen"
    "title_challenged_side": " Dies ist der Kommentar, der in Frage gestellt wurde. Stimmen Sie zu, wenn Sie dem Kommentator zustimmen."
    "title_challenger_side": " Dies ist die Meinung des Herausforderers. Stimmen Sie ab, wenn Sie der gegengesetzten Ansicht zustimmen."
    "title_reply_comment": "Kommentieren Sie die Meinung"
    "title_reply_question": " Kommentieren Sie diese Frage"
    "title_reply_answer": " Kommentieren Sie diese Antwort"
    "title_reply_challenge": "Kommentarieren Sie die Herausforderung"
    "title_question_answer": " Beantworten Sie diese Frage"
    "title_answer_note": " Dies ist eine Antwort auf die obige Frage"
    "title_is_question": " Prüfen Sie dies, wenn Sie eine Frage posten"
    "title_logo": " BurnZone Kommentar"
    "new_notifications": " {value}"
    "user_notif_NEW_CONVERSATION": " Ein neuer Artikel wurde am {sitename} veröffentlicht"
    "user_notif_WIN_QUESTION": " Sie hatten die beste Antwort!"
    "user_notif_WIN_QUESTION_here": " Sie hatten die beste Antwort!"
    "user_notif_NEW_COMMENT": " Neuer Kommentar"
    "user_notif_NEW_COMMENT_here": " Neuer Kommentar"
    "user_notif_ANSWER": " {username} beantwortete Ihrem Kommentar"
    "user_notif_ANSWER_here": " {username} beantwortete Ihrem Kommentar"
    "user_notif_REPLY": " {username} beantwortete Ihrem Kommentar"
    "user_notif_REPLY_here": " {username} beantwortete Ihrem Kommentar "
    "user_notif_CHALLENGED": " {username} fordert Ihr Kommentar heraus"
    "user_notif_CHALLENGED_here": " {username} fordert Ihr Kommentar heraus"
    "user_notif_NEW_CHALLENGE": " Neue Herausforderung"
    "user_notif_NEW_CHALLENGE_here": " Neue Herausforderung"
    "user_notif_WIN_CHALLENGE": " Sie haben Ihre Herausforderung gewonnen!"
    "user_notif_WIN_CHALLENGE_here": "Sie haben Ihre Herausforderung gewonnen!"
    "user_notif_LOSE_CHALLENGE": "Sie haben Ihre Herausforderung verloren!"
    "user_notif_LOSE_CHALLENGE_here": "Sie haben Ihre Herausforderung verloren!"
    "user_notif_VOTE": " {username} stimmte für Sie in einer Herausforderung"
    "user_notif_VOTE_here": " {username} stimmte für Sie in einer Herausforderung"
    "user_notif_VOTE_down": " Jemand hat die Abstimmung für Sie in einer Herausforderung rückgängig gemacht"
    "user_notif_VOTE_down_here": " Jemand hat die Abstimmung für Sie in einer Herausforderung rückgängig gemacht"
    "user_notif_LIKE_ANSWER": " {username} gefällt Ihre Antwort"
    "competitions": "Wettbewerbe"
    "competition_banner": "Wettbewerb: <strong> {title} </strong> {start} bis {end}, lesen Sie die <a target='_blank' href='{rules}'> Regeln </a> und mitreden </a> "
    "competition_header": "<i class='icon-trophy'> </i> Gewinnen <a href='{prize_url}'> {prize} </a> durch den Beitritt der {community} Gemeinde und Kommentierung zwischen {start} - {end} (<span class='countdown'> {Countdown} </span> Rest, siehe <a target='_blank' href='{rules}'> Regeln </a>) "
    "competition_starts_on": "Der Wettbewerb beginnt am"
    "competition_active": "Wettbewerb ist aktiv"
    "competition_ended_on": "Der Wettbewerb endete am"
    "competition_active_until": "Der Wettbewerb aktiv, bis"
    "competition_winner": "Winner"
    "competition_rules": "Regeln"
    "competition_prize": "Preis"
    "competition_ranking_title": "Der Wettbewerb Rangfolge"
    "user_notif_COMPETITION_START": "Der Wettbewerb hat begonnen: {title}"
    "user_notif_COMPETITION_STARTING": "{days} Tage, bis der Wettbewerb beginnt: {title}"
    "user_notif_COMPETITION_END": "Der Wettbewerb endete: {title}"
    "user_notif_COMPETITION_ENDING": "Der Wettbewerb {title} endet in {days} Zeit"
    "submit_comment": "Kommentar Abgeben"
    "submit_question": "Frage absenden"
    "reg_and_submit_comment": "Registrieren"
}

