module.exports = {
  name: "Español"
  code: "es"
  terms:
    "browser_support": " Burnzone no es compatible con tu navegador. Por favor, actualiza tu navegador a la última versión o cambia tu tavegador por Mozilla o Chrome."
    "login_to_comment": " Inicia sesión para comentar"
    "login_to_challenge": "Inicia sesión para desafiar"
    "login_with": "Inicia sesión con"
    "signup_with": " Regístrate con "
    "sign_in": "Accede"
    "sign_in_using": "Accede utilizando"
    "settings": "Configuración"
    "or": " o"
    "comment": "Comentario"
    "comments": "Comentarios"
    "challenges": "Desafíos"
    "questions": "Preguntas"
    "likes": "me gusta"
    "write_comment": "Comparte tus pensamientos ..."
    "write_answer": "Escribe tu respuesta aquí"
    "answered": "contestado"
    "submit": "Enviar"
    "cancel": "Cancelar"
    "sort_by": "ordenado por"
    "get_burnzone": " Consigue BurnZone Comentando"
    "oldest": " El más antiguo"
    "newest": " El más nuevo"
    "points": " Puntos"
    "points_short": " pts"
    "answers": " Respuestas"
    "votes": " Votos"
    "no_points": " {value} Puntos"
    "reply": " Responder"
    "reply_in_challenge": " Responder en el desafío"
    "comment_in_challenge": " Comentar en el desafío"
    "challenge": " Desafío"
    "question": "Pregunta"
    "key_point": " Punto clave"
    "no_all_activities": " {value} Comentario (s)"
    "no_comments": " {value} comentario (s)"
    "no_challenges": " {value} desafío (s)"
    "no_questions": " {value} pregunta (s)"
    "no_answers": " {value} respuesta (s)"
    "enter_your_pv": " Introduzca su punto de vista ..."
    "vs": " vs"
    "enter_fb_uid": " Introduzca usuario de Facebook aquí"
    "non_verified_user": "La dirección de correo electrónico de este usuario no ha sido verificada"
    "logout": " Salir"
    "gravatar_profile": " Perfil en Gravatar"
    "days_ago": " Hace {value} día (s) "
    "hours_ago": " Hace {value} hora (s)"
    "minutes_ago": " Hace {value} minuto (s)"
    "ends_in_days": " Finaliza en {value} día(s)"
    "ends_in_hours": " Finaliza en {value} hora(s)"
    "ends_in_minutes": " Finaliza en {value} minuto(s)"
    "challenge_ended": " Finalizada"
    "ends_now": "Debería terminar en cualquier momento"
    "just_now": " en este momento"
    "exact_time": " en {value}"
    "my_profile": " Mi perfil"
    "challenge_comment": "Punto de vista del retador:"
    "original_comment": "Resumen del punto cuestionado:"
    "or_login_with": "o inicia sesión con"
    "flag": "Bandera"
    "answer": "Respuesta"
    "share": "Comparte"
    "share_challenge": " Comparte este desafío:"
    "share_conversation": " Comparte esta conversación"
    "share_tw": " Compartir en twitter"
    "share_fb": " Compartir en Facebook"
    "error_loading": " No pudimos cargar esta conversación."
    "error_embed_sitenotexists": " Nombre de la página no válido."
    "error_embed_nourl": " URL de conversación no válido."
    "error_embed_embedlocalhost": " No se puede insertar una conversación en la web de BurnZone."
    "error_embed_forceid": " Tu cuenta BurnZone  está configurada para forzar IDs de conversación pero no proporcionaste ninguna."
    "error_embed_useqs": "Tu cuenta BurnZone está configurada para utilizar claves de cadena de consulta pero no las proporcionaste todas."
    "error_embed_url_not_reachable": " Tu artículo debe ser de acceso público en internet."
    "flagged": " Marcado"
    "flagged_challenge": " Este reto se ha marcado"
    "change_image": " Establece tu imagen"
    "change_your_data": " Cambiar los datos del perfil"
    "change_name": " Nombre"
    "change_email": " Email"
    "change_submit": " Cambio"
    "use_grav_image": " Gravatar"
    "use_fb_image": " Facebook"
    "error_access_api": " Hubo un problema procesando tu solicitud"
    "user_banned": "Se te ha prohibido el acceso por el momento"
    "create_comment_success": " Tu comentario ha sido creado con éxito"
    "create_question_success": "Tu pregunta ha sido creada con éxito"
    "create_answer_success": "Tu respuesta ha sido creada con éxito"
    "create_comment_notallowed": "Se te ha prohibido comentar por el momento"
    "create_comment_approval": " Tu comentario está a la espera de la aprobación del moderador"
    "create_question_approval": " Tu pregunta está  a la espera de la aprobación del moderador"
    "create_answer_approval": " Tu respuesta está  a la espera de la aprobación del moderador"
    "create_challenge_success": "Tu desafío ha sido creado con éxito"
    "create_challenge_notallowed": "Se te ha prohibido realizar comentarios desafiantes por el momento"
    "create_challenge_approval": "Tu desafío aguarda la aprobación del moderador"
    "create_challenge_notpoints": "No tienes suficientes puntos para desafiar este comentario"
    "create_challenge_denied": " No puedes desafiar  tu propio comentario, un comentario que no existe, un comentario eliminado o un comentario que ya ha sido desafiado (el desafío podría no ser aprobado)"
    "vote_commentinch_user_in_challenge": "No puedes votar porque estás en el desafío"
    "vote_commentinch_once": " Puedes votar solo una vez y solo puedes retractarte de tu voto anterior"
    "vote_ch_ended": "No puedes votar en un reto que ha terminado"
    "like_comment_once": "Puedes dar a me gusta solo una vez y solo puedes retractarte de tu me gusta anterior"
    "like_comment_retry": " Hubo un conflicto en tu solicitud. Por favor, inténtalo de nuevo."
    "like_own_comment": "No puedes darle a me gusta a tu propio comentario"
    "like_author_unknown": " Alguien"
    "needs_login": " Tienes que iniciar sesión primero"
    "needs_moderator": " Necesitas permisos de moderador para esto"
    "user_exists": " Esta dirección de correo electrónico ya está siendo utilizada por otro usuario. Por favor, prueba otra."
    "edit_profile": "Puedes cambiar tu nombre y avatar en tu página de perfil"
    "delete": " Borrar"
    "top_answer": "Respuesta más común"
    "create_user": " O crear un usuario BurnZone"
    "create_user_expl": " Crear un usuario te permitirá comentar, votar y ser parte de la tabla de clasificación."
    "anon_name": " Nombre"
    "anon_email": " Email"
    "anon_pass": " Contraseña"
    "invalid_name": " Por favor, introduce un nombre"
    "invalid_email": " Por favor, introduce una dirección de email válida"
    "invalid_password": " Por favor, introduce una contraseña válida"
    "email_must_be_valid": " Debe ser válida para verificar"
    "site_leaderboard": " Tabla de clasificación de la web"
    "conversation_leaderboard": " Tabla de clasificación de Conversaciones"
    "site_leaderboard_title": " Estas clasificaciones se basan en todas las actividades que tienen los usuarios en toda la web"
    "conversation_leaderboard_title": " Estas clasificaciones se basan en la actividad en este artículo únicamente"
    "how_to_points": " ¿Cómo consigo puntos?"
    "not_verified": "Tu dirección de correo electrónico no se ha verificado. No se te permite marcar contenido inapropiado y puedes votar un número limitado de veces."
    "no_password": "No has establecido una contraseña todavía y podrías perder tu cuenta. <a href=\"#{"#profile"}\"> Ve a tu perfil </a> a continuación, haz click en \" Cambiar contraseña \" para configurar la contraseña de tu cuenta."
    "change_pass": " <a href=\"{url}/profile\" target=\"_blank\"> cambio de contraseña </a>."
    "change_notifications": " <a href=\"{url}/profile\" target=\"_blank\"> Cambiar las opciones de notificación </a>."
    "subscription_options": " Opciones de suscripción"
    "subscribe": " Suscribirse"
    "subscribe_own": " Suscríbete a mi propio contenido"
    "subscribe_auto": " Auto suscribirse a las conversaciones en las que tomo parte"
    "subscribe_conversations": " Suscríbete a nuevos artículos"
    "subscribe_updates": " Suscribirse a las actualizaciones en esta conversación"
    "subscribe_success": "Te has suscrito con éxito"
    "unsubscribe_success": " Te has dado de baja en la subscripción con éxito"
    "read_more": " (Leer más)"
    "read_less": "(Leer menos)"
    "show_more": " Mostrar más"
    "delete_all": " Eliminar todo"
    "format_text": "Dar formato al texto"
    "challenge_ad_text": " ¿No estás de acuerdo con un comentario?"
    "challenge_ad_text_2": " Desafíalo para recibir puntos."
    "learn_more": " Más información"
    "best_answer": " Mejor respuesta"
    "challenged_comment": "Comentario desafiado"
    "challenged_question": " Pregunta desafiada"
    "go_to_comments": " Volver a los comentarios"
    "is_question": " Esto es una pregunta"
    "comment_deleted": " Este comentario ha sido eliminado"
    "question_deleted": " Esta pregunta ha sido eliminada"
    "answer_deleted": " Esta respuesta ha sido eliminada"
    "challenge_deleted": " Este desafío ha sido borrado"
    "said": " dicho"
    "challenged": " desafiado"
    "challenge_winner": " Ganador del desafío"
    "title_like_up": "Da a me gusta en el comentario"
    "title_like_down": "Da a no me gusta en el comentario"
    "title_best_answer": " Esta es la mejor respuesta, en base a los votos recibidos"
    "title_challenged": " Este comentario ha sido retado"
    "title_reply": " Responder a este comentario"
    "title_challenge": "Desafía este comentario para compartir un punto de vista opuesto"
    "title_share": " Comparte esto en los medios sociales"
    "title_flag": " Marcar como spam"
    "title_vote_up": " Voto positivo"
    "title_vote_down": "Retraerse del voto"
    "title_challenged_side": " Este es el comentario que fue desafiado. Vota si estás de acuerdo con el comentarista."
    "title_challenger_side": " Esta es la opinión del retador. Vota si estás de acuerdo con su punto de vista opuesto."
    "title_reply_comment": " Comentar esta opinión"
    "title_reply_question": " Comentar esta pregunta"
    "title_reply_answer": " Comenta esta respuesta"
    "title_reply_challenge": " Comentar este desafío"
    "title_question_answer": " Responder a esta pregunta"
    "title_answer_note": " Esta es una respuesta a la pregunta anterior"
    "title_is_question": "Comprueba esto si estás subiendo una pregunta"
    "title_logo": "Comentar BurnZone "
    "new_notifications": " {value}"
    "user_notif_NEW_CONVERSATION": " Un nuevo artículo fue publicado en {sitename}"
    "user_notif_WIN_QUESTION": "¡Tenías la mejor respuesta!"
    "user_notif_WIN_QUESTION_here": "¡Tenías la mejor respuesta!"
    "user_notif_NEW_COMMENT": " Nuevo comentario"
    "user_notif_NEW_COMMENT_here": " Nuevo comentario"
    "user_notif_ANSWER": " {username} respondió a tu comentario"
    "user_notif_ANSWER_here": " {username} respondió a tu comentario"
    "user_notif_REPLY": " {username} respondió a tu comentario"
    "user_notif_REPLY_here": " {username} respondió a tu comentario"
    "user_notif_CHALLENGED": " {username} desafió tu comentario"
    "user_notif_CHALLENGED_here": " {username} desafió tu comentario"
    "user_notif_NEW_CHALLENGE": " Nuevo desafío"
    "user_notif_NEW_CHALLENGE_here": " Nuevo desafío"
    "user_notif_WIN_CHALLENGE": "¡Has ganado tu desafío!"
    "user_notif_WIN_CHALLENGE_here": "¡Has ganado tu desafío!"
    "user_notif_LOSE_CHALLENGE": "¡Has perdido tu desafío!"
    "user_notif_LOSE_CHALLENGE_here": "¡Has perdido tu desafío!"
    "user_notif_VOTE": " {username} te votó en un desafío"
    "user_notif_VOTE_here": "  {username} te votó en un desafío"
    "user_notif_VOTE_down": " Alguien se retractó de su voto a tu favor en un desafío"
    "user_notif_VOTE_down_here": " Alguien se retractó de su voto a tu favor en un desafío"
    "user_notif_LIKE_ANSWER": " A {username} le gusta tu respuesta"
    "competitions": "Concursos"
    "competition_banner": "La competencia: <strong> {title} </strong> de {start} a {end}; leer el <a target='_blank' href='{rules}'> Rules </a> y unirse a la conversación </a> "
    "competition_header": "<i Class='icon-trophy'> </i> Ganar <a href='{prize_url}'> {prize} </a> por unirse a la {community} comunidad y comentando entre {start} - {end} (<span class='countdown'> {countdown} </span> restante, consulte <a target='_blank' href='{rules}'> reglas </a>) "
    "competition_starts_on": "La competencia comienza el"
    "competition_active": "La competencia está activo"
    "competition_ended_on": "La competencia terminó en"
    "competition_active_until": "La competencia activa hasta que"
    "competition_winner": "Ganador"
    "competition_rules": "Reglas"
    "competition_prize": "Premio"
    "competition_ranking_title": "La competencia Clasificación"
    "user_notif_COMPETITION_START": "La competencia comenzó: {title}"
    "user_notif_COMPETITION_STARTING": "{days} días hasta que comience la competición: {title}"
    "user_notif_COMPETITION_END": "Terminó Competición: {title}"
    "user_notif_COMPETITION_ENDING": "La competencia {title} finalizando en {days} días"
    "submit_comment": "Enviar comentario"
    "submit_question": "Enviar pregunta"
    "reg_and_submit_comment": "Registro"
}

