module.exports = {
  name: "Pусский язык"
  code: "ru"
  terms:
    "browser_support": "Burnzone не поддерживается вашим браузером. Пожалуйста, обновите свой браузер до новейшей версии или смените его на Mozilla или Chrome."
    "login_to_comment": "Чтобы комментировать, войдите под своим логином и паролем"
    "login_to_challenge": "Чтобы оспорить, войдите под своим логином и паролем"
    "login_with": "Войти с помощью"
    "signup_with": "Зарегистрироваться с помощью"
    "sign_in": "Авторизоваться"
    "sign_in_using": "Авторизоваться с помощью"
    "settings": "настройки"
    "or": "или"
    "comment": "Комментировать"
    "comments": "Комментарии"
    "challenges": "Споры"
    "questions": "Вопросы"
    "likes": "нравится"
    "write_comment": "Поделиться своими мыслями …"
    "write_answer": "Введите здесь свой ответ"
    "answered": "ответил(а)"
    "submit": "Отправить"
    "cancel": "Отменить"
    "sort_by": "отсортированы по"
    "get_burnzone": "Получить BurnZone Commenting"
    "oldest": "Самые старые"
    "newest": "Самые новые"
    "points": "Очки"
    "points_short": "очков"
    "answers": "Ответы"
    "votes": "Голоса"
    "no_points": "Очков: {value}"
    "reply": "Ответить"
    "reply_in_challenge": "Ответить в споре"
    "comment_in_challenge": "Комментировать в споре"
    "challenge": "Спор"
    "question": "Вопрос"
    "key_point": "Ключевой момент"
    "no_all_activities": "Комментариев: {value}"
    "no_comments": "Комментариев: {value}"
    "no_challenges": "Комментариев: {value}"
    "no_questions": "Вопросов: {value}"
    "no_answers": "Ответов: {value}"
    "enter_your_pv": "Введите свою точку зрения ..."
    "vs": "против"
    "enter_fb_uid": "Введите здесь идентификатор пользователя Facebook"
    "non_verified_user": "Адрес электронной почты этого пользователя не был проверен"
    "logout": "Выйти"
    "gravatar_profile": "Профиль на Gravatar"
    "days_ago": "{value} дн. назад"
    "hours_ago": "{value} час. назад"
    "minutes_ago": "{value} минут. назад"
    "ends_in_days": "Заканчивается через {value} дн."
    "ends_in_hours": "Заканчивается через {value} час."
    "ends_in_minutes": "Заканчивается через {value} мин."
    "challenge_ended": "Закончен"
    "ends_now": "Должен закончиться в любую минуту"
    "just_now": "прямо сейчас"
    "exact_time": "в {value}"
    "my_profile": "Мой профиль"
    "challenge_comment": "Точка зрения спорщика:"
    "original_comment": "Резюме оспариваемой точки зрения:"
    "or_login_with": "или авторизуйтесь с помощью"
    "flag": "Флаг"
    "answer": "Ответ"
    "share": "Поделиться"
    "share_challenge": "Поделиться этим спором:"
    "share_conversation": "Поделиться этим разговором"
    "share_tw": "Поделиться на Twitter"
    "share_fb": "Поделиться на Facebook"
    "error_loading": "Мы не смогли загрузить этот разговор."
    "error_embed_sitenotexists": "Неправильное название сайта."
    "error_embed_nourl": "Неправильный URL разговора."
    "error_embed_embedlocalhost": "Не могу вставить разговор на сайт BurnZone."
    "error_embed_forceid": "Ваша учетная запись на BurnZone настроена на обязательное предоставление идентификаторов разговоров, но вы его не предоставили."
    "error_embed_useqs": "Ваш BurnZone счета настроен на использование ключей строковых запросов, но вы не предоставили все ключи."
    "error_embed_url_not_reachable": "Ваша статья должны быть публично доступна в Интернете."
    "flagged": "Отмечено флажком"
    "flagged_challenge": "Этой спор был отмечен флажком"
    "change_image": "Установите свое изображение"
    "change_your_data": "Изменить данные вашего профиля"
    "change_name": "Имя"
    "change_email": "E-mail"
    "change_submit": "Изменить"
    "use_grav_image": "Gravatar"
    "use_fb_image": "Facebook"
    "error_access_api": "При обработке вашего запроса возникла проблема"
    "user_banned": "На данный момент вы под запретом"
    "create_comment_success": "Ваш комментарий был успешно создан"
    "create_question_success": "Ваш вопрос был успешно создан"
    "create_answer_success": " Ваш ответ был успешно создан"
    "create_comment_notallowed": "На данный момент вам запрещено делать комментарии"
    "create_comment_approval": "Ваш комментарий ожидает одобрения модератора"
    "create_question_approval": "Ваш вопрос ожидает одобрения модератора"
    "create_answer_approval": "Ваш ответ ожидает одобрения модератора"
    "create_challenge_success": "Ваша спор был успешно создан"
    "create_challenge_notallowed": "На данный момент вам запрещено делать оспаривающие комментарии"
    "create_challenge_approval": "Ваш спор ожидает одобрения модератора"
    "create_challenge_notpoints": "У вас недостаточно очков, чтобы оспорить это комментарий"
    "create_challenge_denied": "Вы не можете оспорить свой собственный комментарий, комментарий, который не существует, удаленный комментарий или комментарий, который был оспорен (разрешение на конкретный спор не может быть отменено)"
    "vote_commentinch_user_in_challenge": "Вы не можете голосовать, потому что находитесь в споре"
    "vote_commentinch_once": "Вы можете голосовать только один раз и можете отказаться только от своего предыдущего голоса"
    "vote_ch_ended": "Вы не можете голосовать в споре, который закончился"
    "like_comment_once": "Вы можете ставить \"лайк\" (\"мне нравится\") только один раз и можете отказаться только своего предыдущего \"лайка\""
    "like_comment_retry": "В вашем запросе был конфликт. Пожалуйста, повторите попытку."
    "like_own_comment": "Вы не можете ставить \"лайк\" на свой собственный комментарий"
    "like_author_unknown": "Кто-то"
    "needs_login": "Вы должны сначала войти под своим логином и паролем"
    "needs_moderator": "Для этого вам нужны права модератора"
    "user_exists": "Этот адрес электронной почты уже используется другим пользователем. Пожалуйста, попробуйте другой адрес."
    "edit_profile": "Вы можете изменить свое имя и аватар на странице профиля"
    "delete": "Удалить"
    "top_answer": "Топ-ответ"
    "create_user": "или создать пользователя BurnZone"
    "create_user_expl": "Создание пользователя позволит вам комментировать, голосовать и быть на доске лидеров."
    "anon_name": "Имя"
    "anon_email": "E-mail"
    "anon_pass": "Пароль"
    "invalid_name": "Пожалуйста, введите имя"
    "invalid_email": "Пожалуйста, введите действующий адрес электронной почты"
    "invalid_password": "Пожалуйста, введите отвечающий правилам пароль"
    "email_must_be_valid": "Должен быть действующим для целей проверки"
    "site_leaderboard": "Таблица лидеров сайта"
    "conversation_leaderboard": "Таблица разговоров-лидеров"
    "site_leaderboard_title": "Эти рейтинги основаны на всех видах активности пользователей на всем сайте"
    "conversation_leaderboard_title": "Эти рейтинги основаны на активности на одной этой статье"
    "how_to_points": "Как я могу получить баллы?"
    "not_verified": "Ваш адрес электронной почты не проверен. Вы не можете отмечать фланком нежелательный контент и можете голосовать ограниченное количество раз."
    "no_password": "Вы еще не установили пароль и можете потерять свой аккаунт. <a href=\"#{"#profile"}\"> Перейдите в профиль</a>, выберите пункт \"Изменение пароля\" и установите пароль для своей учетной записи."
    "change_pass": "<a href=\"{url}/profile\" target=\"_blank\">Изменение пароля</>."
    "change_notifications": "<a href=\"{url}/profile\" target=\"_blank\"> Изменение параметров уведомлений </a>."
    "subscription_options": "Параметры подписки"
    "subscribe": "Подписаться"
    "subscribe_own": "Подписаться на мой собственный контент"
    "subscribe_auto": "Автоматически подписаться на разговоры, в которых я участвую"
    "subscribe_conversations": "Подписаться на новые статьи"
    "subscribe_updates": "Подписаться на обновления этой беседы"
    "subscribe_success": "Вы успешно подписались"
    "unsubscribe_success": "Вы успешно отписались"
    "read_more": "(читать больше)"
    "read_less": "(читать меньше)"
    "show_more": "Показать больше"
    "delete_all": "Удалить все"
    "format_text": "Форматирование текста"
    "challenge_ad_text": "Не согласны с комментарием?"
    "challenge_ad_text_2": "Оспорьте его, чтобы получить очки."
    "learn_more": "Узнать подробнее"
    "best_answer": "Наилучший ответ"
    "challenged_comment": "Оспоренный комментарий"
    "challenged_question": "Оспоренный вопрос"
    "go_to_comments": "Вернуться к комментариям"
    "is_question": "Это вопрос"
    "comment_deleted": "Этот комментарий был удален"
    "question_deleted": "Этот вопрос был удален"
    "answer_deleted": "Этот ответ был удален"
    "challenge_deleted": "Этот спор был удален"
    "said": "указанный"
    "challenged": "спор"
    "challenge_winner": "Победитель спора"
    "title_like_up": "Поставить \"лайк\" (\"мне нравится\") этому комментарию"
    "title_like_down": "Поставить \"дислайк\" (\"мне не нравится\") этому комментарию"
    "title_best_answer": "Это наилучший ответ на основе полученных голосов"
    "title_challenged": "Этот комментарий был оспорен"
    "title_reply": "Ответить на этот комментарий"
    "title_challenge": "Оспорьте этот комментарий, чтобы поделиться противоположным мнением"
    "title_share": "Рассказать об этом в социальных сетях"
    "title_flag": "Отметить как спам"
    "title_vote_up": "Голосовать за"
    "title_vote_down": "Отказаться от голоса"
    "title_challenged_side": "Это комментарий был оспорен. Голосовать, если вы согласны с комментирующим."
    "title_challenger_side": "Это мнение оспорившего. Голосовать, если вы согласны с его противоположной точкой зрения."
    "title_reply_comment": "Прокомментировать это мнение"
    "title_reply_question": "Прокомментировать этот вопрос"
    "title_reply_answer": "Прокомментировать этот ответ"
    "title_reply_challenge": "Прокомментировать этот вызов"
    "title_question_answer": "Ответить на этот вопрос"
    "title_answer_note": "Это ответ на поставленный выше вопрос"
    "title_is_question": "Посмотрите на это, если вы публикуете вопрос"
    "title_logo": "BurnZone Commenting"
    "new_notifications": "{value}"
    "user_notif_NEW_CONVERSATION": "На {sitename} была опубликована новая статья"
    "user_notif_WIN_QUESTION": "У вас был наилучший ответ!"
    "user_notif_WIN_QUESTION_here": "У вас был наилучший ответ!"
    "user_notif_NEW_COMMENT": "Новый комментарий"
    "user_notif_NEW_COMMENT_here": "Новый комментарий"
    "user_notif_ANSWER": "{username} дал ответ на ваш комментарий"
    "user_notif_ANSWER_here": "{username} дал ответ на ваш комментарий"
    "user_notif_REPLY": "{username} ответил на ваш комментарий"
    "user_notif_REPLY_here": "{username} ответил на ваш комментарий"
    "user_notif_CHALLENGED": "{username} оспорил ваш комментарий"
    "user_notif_CHALLENGED_here": "{username} оспорил ваш комментарий"
    "user_notif_NEW_CHALLENGE": "Новый спор"
    "user_notif_NEW_CHALLENGE_here": "Новый спор"
    "user_notif_WIN_CHALLENGE": "Вы выиграли свой спор!"
    "user_notif_WIN_CHALLENGE_here": "Вы выиграли свой спор!"
    "user_notif_LOSE_CHALLENGE": "Вы проиграли свой спор!"
    "user_notif_LOSE_CHALLENGE_here": "Вы проиграли свой спор!"
    "user_notif_VOTE": "{username} проголосовал за вас в споре"
    "user_notif_VOTE_here": "{username} проголосовал за вас в споре"
    "user_notif_VOTE_down": "Кто-то отказался от голоса за вас в споре"
    "user_notif_VOTE_down_here": "Кто-то отказался от голоса за вас в споре"
    "user_notif_LIKE_ANSWER": "Пользователю {username} понравился ваш ответ"
    "competitions": "Конкурсы"
    "competition_banner": "Конкуренция: <strong> {title} </ STRONG> от {start} до {end}; читать <a target='_blank' href='{rules}'> Правила </a> и присоединиться к разговору </a> "
    "competition_header": "<i Class='icon-trophy'> </i> Доля <a href='{prize_url}'> {prize} </a>, присоединившись к {community} сообщество и комментируя между {start} - {end} (<span class='countdown'> {countdown} </ span> остальные, см. <a target='_blank' href='{rules}'> правила </a>) "
    "competition_starts_on": "Конкуренция начинается"
    "competition_active": "Конкуренция активен"
    "competition_ended_on": "Конкуренция закончилась"
    "competition_active_until": "Конкуренция активным до"
    "competition_winner": "Победитель"
    "competition_rules": "Правила"
    "competition_prize": "Выигрыш"
    "competition_ranking_title": "Конкуренция Рейтинг"
    "user_notif_COMPETITION_START": "Конкуренция начал: {title}"
    "user_notif_COMPETITION_STARTING": "{days} дней, пока не начнется конкуренции: {title}"
    "user_notif_COMPETITION_END": "Конкуренция закончилась: {title}"
    "user_notif_COMPETITION_ENDING": "Конкуренция {title} заканчивается в {days} дней"
    "submit_comment": "Представьте комментарий"
    "submit_question": "Представьте вопрос"
    "reg_and_submit_comment": "Регистрация"
}
